### ISSUE TITLE
Degradation in 1.29: Support for CentOS7

### ISSUE THREAD

**Issue by pyhedgehog** [arkane-systems/genie#104]
Usage of machinectl should be customizable.
In Debian everything is fine, but under CentOS7 I have:
```console
[root@honeypot ~]# genie --version
1.28
[root@honeypot ~]# echo ${INSIDE_GENIE:-false}
false
[root@honeypot ~]# genie -s
runuser: invalid option -- 'w'

Usage:
 runuser [options] -u <USER> COMMAND
 runuser [options] [-] [USER [arg]...]

Run COMMAND with the effective <user> id and group id. If -u not
given, fallback to su(1) compatible semantic and shell is executed.
The options -l, -c, -f, -s are mutually exclusive to -u.

Options:
 -u, --user <user>               username
 -m, -p, --preserve-environment  do not reset environment variables
 -g, --group <group>             specify the primary group
 -G, --supp-group <group>        specify a supplemental group

 -, -l, --login                  make the shell a login shell
 -c, --command <command>         pass a single command to the shell with -c
 --session-command <command>     pass a single command to the shell with -c
                                 and do not create a new session
 -f, --fast                      pass -f to the shell (for csh or tcsh)
 -s, --shell <shell>             run shell if /etc/shells allows it

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see runuser(1).
genie: starting shell failed; nsenter returned 1.
[root@honeypot ~]# genie -c bash
[root@honeypot-wsl ~]# echo $INSIDE_GENIE
true
```
It's almost OK (except unsupported `--whitelist-environment` in `runuser`), but after upgrade:
```console
[root@honeypot ~]# genie --version
1.31
[root@honeypot ~]# genie -s
Unknown operation shell.
genie: starting shell failed; machinectl shell returned 1.
[root@honeypot ~]# genie -c bash
Unknown operation shell.
genie: running command failed; machinectl shell returned 1.
genie: running command failed; machinectl shell returned 1.
[root@honeypot ~]# genie -l

** (pkttyagent:828): WARNING **: 01:16:07.893: Unable to register authentication agent: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown:
The name org.freedesktop.PolicyKit1 was not provided by any .service files
Error registering authentication agent: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.PolicyKit1 was not prov
ided by any .service files (g-dbus-error-quark, 2)
Failed to get machine PTY: The name org.freedesktop.machine1 was not provided by any .service files
genie: starting login failed; machinectl login returned 1.
```

**Comment by cerebrate** [comment]
Huh. Seems like Centos systemd is an older version (219 vs. 241 as of Debian buster; heck, it was 232 back in stretch).

**Comment by pyhedgehog** [comment]
What about something like `use-machinectl=false` in `/etc/genie.ini` to return to 1.28 behaviour?
From my PoV it's better than distribution-specific patches.

**Comment by cerebrate** [comment]
The main reason I don't want to do that is because it adds back dependencies, and more relevantly, adds more possibilities to the existing problem of supporting features I don't use on distros I don't use.

With a Centos maintainer - hell, if someone else just wants to compile 1.28 from the tag and maintain that as a Centos package - I'm not making more work for myself by doing it.

**Comment by PavelSosin-320** [comment]
CentOS7 or 8 ? They are not supported by RedHat and maintainer. [CentOS WSL distro](https://github.com/wsldl-pg/CentWSL) it is better Fedora or Stream. For Fedora 33 it works. Fedora is like Ubuntu and it is not necessary to wait 2 years until the next release. Maybe [wsldl CentWSL ](https://github.com/wsldl-pg/CentWSL) can help to maintain genie?
P.S. I tried UBI8 OCI image - it is perfect!

**Comment by cerebrate** [comment]
On further consideration, my official answer on support for this and other distros with older versions of systemd is going to be "download the binaries for, or compile, 1.28". As said elsewhere (#99), I just don't have the time or resources to manage all the possible distro-specific variations.

**Comment by pyhedgehog** [comment]
@cerebrate What additional dependencies you mean? As I can see in [genie/debian/control](https://github.com/arkane-systems/genie/compare/1.27...1.29#diff-252c5945ae0a9fe85490fce3f73d2f39b95438c2f8c579a78d3f7d7e4e827bb4L13) dependency list was increased after switching to `machinectl`.

But I understood that support of old distributions is not in your wishlist. (-:

@PavelSosin-320 There are situations when you have to support same distribution as on legacy server.

**Comment by cerebrate** [comment]
@pyhedgehog I admit, I wasn't really counting the addition of systemd-machined as a new dependency, since in practice that just seems to mean "a recent systemd".

Mostly, though, I was thinking of eliminating _runuser(1)_ as required, especially as I've had other compatibility problems with it before, like the -w issue you mentioned. (Also, huh, looks like the earlier packaging was wrong in not mentioning a dependence on the 'util-linux' package. Oops.)

There's also some stuff that hadn't yet made it into genie yet (implementing it automatically being an ugly kluge) intended to compensate for _runuser -l_'s simulation of a login environment not actually being a login environment, showing up in lots of minor glitches, and so requiring some hacking of the _/etc/pam.d_ contents to make it work exactly right. Going through _machinectl shell_ or _machinectl login_, as far as I can tell, eliminates the need for all of that.

**Comment by PavelSosin-320** [comment]
@pyhedgehog Most of WSL distro images are only the repacked  Cloud VM or OCI Images. When a maintainer like RedHat decides to cut the support of the original distro the WSL distro dies because it has no own package repositories. All new versions, bug corrections, including security corrections will arrive only to the original distro repositories. WSL can't be used for production. As a development environment, it can be only ahead of the production version. An excellent example is RedHat production RHEL8.0 and OCI image for development UBI8 that is 8.2

**Comment by cerebrate** [comment]
@pyhedgehog A thought occurred to me, and I just gave it a try --

LXD ( https://linuxcontainers.org/lxd/getting-started-cli/ ) works happily under genie, and having just tested it, it's happy to run a Centos 7 LXC container, too.

```
❯ lxc launch images:centos/7 testcentos                                                                                                                            Creating testcentos
Starting testcentos

❯ lxc list                                                                                                                                                         +------------+---------+---------------------+-----------------------------------------------+-----------+-----------+
|    NAME    |  STATE  |        IPV4         |                     IPV6                      |   TYPE    | SNAPSHOTS |
+------------+---------+---------------------+-----------------------------------------------+-----------+-----------+
| testcentos | RUNNING | 10.19.25.113 (eth0) | fd42:315e:adad:a4c5:216:3eff:fe9e:1c8e (eth0) | CONTAINER | 0         |
+------------+---------+---------------------+-----------------------------------------------+-----------+-----------+

❯ lxc exec testcentos -- /bin/bash
[root@testcentos ~]# uname -a
Linux testcentos 5.4.91-20210129-microsoft-custom-wsl2+ #4 SMP Sat Jan 30 14:55:33 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

[root@testcentos ~]# cat /etc/*-release
CentOS Linux release 7.9.2009 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.9.2009 (Core)
CentOS Linux release 7.9.2009 (Core)
```

Being an LXC container, too, there's no significant slowdown. There are a couple of minor glitches in that, being inside a container, a couple of the services that tweak kernel parameters (systemd-sysctl.service, dev-hugepages.mount), but everything else seems to work fine.

**Comment by PavelSosin-320** [comment]
@pyhedgehog Try Fedora33 with Podman 3 running Nginx container in the own Pod using rootless networking. CentoOS7 will never get Podman.
![PodmanNginxContainer Fedora33](https://user-images.githubusercontent.com/54495912/106935033-8c485900-6723-11eb-98d4-327d77c00f25.png)

**Comment by gbraad** [comment]
> CentoOS7 will never get Podman.

This is the ouput of a very old version on EL7 (CentOS)
```
$ rpm -qi podman
 Name        : podman
 Version     : 0.12.1.2
 Release     : 2.git9551f6b.el7.centos
 Architecture: x86_64
 Install Date: Sat 15 Jun 2019 01:43:33 PM EAT
 Group       : Unspecified
 Size        : 33654116
 License     : ASL 2.0
 Signature   : RSA/SHA256, Wed 13 Feb 2019 11:56:49 PM EAT, Key ID 24c6a8a7f4a80eb5
 Source RPM  : podman-0.12.1.2-2.git9551f6b.el7.centos.src.rpm
 Build Date  : Wed 13 Feb 2019 08:05:29 PM EAT
 Build Host  : x86-02.bsys.centos.org
 Relocations : (not relocatable)
 Packager    : CentOS BuildSystem http://bugs.centos.org
 Vendor      : CentOS
 URL         : https://github.com/containers/libpod
 Summary     : Manage Pods, Containers and Container Images
 Description :
 Manage Pods, Containers and Container Images
 libpod provides a library for applications looking to use
 the Container Pod concept popularized by Kubernetes.
```

So CentOS 7 never getting Podman is a wrong conclusion: https://centos.pkgs.org/7/centos-extras-x86_64/ (you might haveto enable epel, but it is there). Anyway, that wasnt the point.

@pyhedgehog At the moment I am looking into enabling systemd on Fedora 33 and CentOS 8. I would consider EL7 not a target for new installations, unless you have to remain 'compatible' with other machines.

**Comment by gbraad** [comment]
Created #114 to track changes for CentOS
