### ISSUE TITLE
Publishing self-contained binaries

### ISSUE THREAD

**Issue by gbraad** [arkane-systems/genie#113]
At the moment the `genie.csproj` specifies:

```xml
   <SelfContained>false</SelfContained>
```

which means that the resulting binary relies on the runtime being available. This means that the distro has to install the needed `dotnet-runtime-5.0` to allow execution.

Is this something that can be considered, as the user might never consider running any other .NET core based application.

**Comment by gbraad** [comment]
This result in the following difference:
```diff
--rwxr-xr-x 1 gbraad gbraad 1303743 Feb 19 14:59 genie
+-rwxr-xr-x 1 gbraad gbraad 63737319 Feb 19 14:57 genie
```

**Comment by cerebrate** [comment]
It's been brought up before, but the resulting binaries explode sufficiently in size that I really don't want to go there in a distributed version; if every utility with dependencies started doing that, the bloat would be nightmarish.

**Comment by gbraad** [comment]
I noticed 61+ MB

**Comment by PavelSosin-320** [comment]
@gbraad Microsoft distributes DotNet runtime in multiple forms and installation methods. But DotNet is not a unique case. NVidia drivers and SDK with all their dependencies are not self-containing too. The installation requires reading of the guide published by NVidia with the version dependencies tables and script snippets for the 1st time installation of the missed dependencies.  Then, if you want to upgrade "please run ...update, .... upgrade before you upgrade the NVidia driver". Every Linux developer knows to do it.

**Comment by gbraad** [comment]
@PavelSosin-320 ??? You are off-topic here.
