### ISSUE TITLE
arch/PKGBUILD is stale

### ISSUE THREAD

**Issue by Kage-Yami** [arkane-systems/genie#115]
It looks like the `arch/PKGBUILD` file is not being updated for new versions that are being released.

I have no idea if you're familiar with how Arch Linux `PKGBUILD`s work, but they are "pinned" to a specific version, and so need the version number inside of it updated at the same time as new releases.

As it stands, given the way it is distributed, all versions will be labelled as `1.32` in Arch Linux, which is rather confusing.

(In my case, I have a system that auto-builds new versions of packages - except currently the version never updates, so the package is never rebuilt.)

**Comment by Kage-Yami** [comment]
I would open a PR, but I don't know how you want to handle the `1.33` and `1.34` tags - delete and recreate the tags with the fixed PKGBUILDs included (a bit of branch shenanigans would be required), or simply release a new `1.35` setting things straight...

**Comment by cerebrate** [comment]
I'm not the Arch PKGBUILD maintainer, so I'm not all up on the details of its packaging, but as I understand it (per [documentation here](https://wiki.archlinux.org/index.php/Creating_packages#pkgver())) the pkgver() function should automatically update the package version from the source when _makepkg_ is run.

**Comment by Kage-Yami** [comment]
Ahh fair point, yes that is right. So the built package will have the right version... so yeah, my problem to solve for my own specific use case. :)

That being said, I notice some recent changes were made. It looks like the package is not actually _built_ anymore as part of the `PKGBUILD`, instead assuming that it is done manually beforehand? Generally, that's not how `PKGBUILD`s work. Even if it's a simple matter of calling `make .` (or something; I don't have any familiarity with make), the `PKGBUILD` should still do that as part of the `build()` function

**Comment by Kage-Yami** [comment]
In the end, the `PKGBUILD` should have everything in it necessary to do _only_:

```sh
makepkg -s
```

... and the Arch Linux package is built completely.

**Comment by cerebrate** [comment]
The build process is under heavy revision right now and is definitely not stable in its current form.

(That said, I myself use only Debian regularly, so in the absence of anyone stepping up to be the Arch package maintainer, it's not unlikely that the end product will be the quickest, dirtiest hack that lets me get a .zst out there when I make a release. I don't really have the time to maintain extra dev environments for all the distros I don't use.)

**Comment by Kage-Yami** [comment]
Sounds fine to me (I unfortunately don't have the capacity to step up as a proper maintainer). A pre-built ZST also works for me for my specific use-case, as I'm already just downloading one of those for a different package. 🙂

**Comment by cerebrate** [comment]
Incidentally, if you get a chance, could you test this Arch package for me? Haven't had a chance to make an Arch test rig yet.

[genie-systemd-1.35-1-x86_64.pkg.tar.zst.gz](https://github.com/arkane-systems/genie/files/6027436/genie-systemd-1.35-1-x86_64.pkg.tar.zst.gz)

**Comment by Kage-Yami** [comment]
Looks good to me; I did the following (starting with 1.33 already installed), and by the end `systemd` was running without issues:

```powershell
wsl genie -s
```

```sh
curl -L https://github.com/arkane-systems/genie/files/6027436/genie-systemd-1.35-1-x86_64.pkg.tar.zst.gz -o genie-systemd-1.35-1-x86_64.pkg.tar.zst.gz
gunzip genie-systemd-1.35-1-x86_64.pkg.tar.zst.gz
sudo pacman -U genie-systemd-1.35-1-x86_64.pkg.tar.zst
exit
```

```powershell
wsl genie -u
wsl --shutdown
wsl genie -i
wsl genie -s
```

```sh
systemctl status
```

Only comment would be that it's weird that the package was double-compressed. (It's already `zstd` compressed, but you've further `gzip`-compressed it)

**Comment by cerebrate** [comment]
Ah, that's just 'cause github won't let you attach a .zst directly to a comment. 😄 When I publish it as an actual release, it'll just be .zst.

(Also, now that I've finished the revisions of the packaging system - and cleared up an issue I was having with symlinks not behaving right for some packages - the PKGBUILD should work the way it's officially supposed to, with the build included.)

**Comment by Kage-Yami** [comment]
Sweet!
