### ISSUE TITLE
typo in rpm build file 

### ISSUE THREAD

**Issue by Krrishdhaneja** [arkane-systems/genie#121]
hi devs, I saw a typo in rpm build file that `dotnet-runtime-5.0` was written as `dotnet-runtme-5.0` so `i` is missing in runtime.
Here is the error I got ->
```Last metadata expiration check: 0:49:53 ago on Wed Feb 24 16:35:03 2021.
Error:
 Problem: conflicting requests
  - nothing provides dotnet-runtme-5.0 needed by genie-1.35-1.fc33.x86_64
(try to add '--skip-broken' to skip uninstallable packages)```

**Comment by cerebrate** [comment]
Nice catch, thanks!

(I fixed it and discreetly swapped out the .rpm in the release, so let's just pretend this never happened... 😁 )

**Comment by Krrishdhaneja** [comment]
Hey when, I was building this tool, I was getting error->
```make  Error 2``` 
Any solution to this?

**Comment by cerebrate** [comment]
That error code alone doesn't tell me anything; I'll need you to include the whole build output.

(Also, please open a new issue for new issues.)

**Comment by gbraad** [comment]
Error sneaked in as the original work didn't include the dotnet-runtime reference. Thanks
