### ISSUE TITLE
Missing Release file?

### ISSUE THREAD

**Issue by Davikar** [arkane-systems/genie#123]
`Getting this message after adding the transdebian stuff and doing apt update:

Ign:5 https://arkane-systems.github.io/wsl-transdebian/apt <distro> InRelease
Err:6 https://arkane-systems.github.io/wsl-transdebian/apt <distro> Release
  404  Not Found [IP: 185.199.111.153 443]
Hit:7 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Reading package lists... Done
E: The repository 'https://arkane-systems.github.io/wsl-transdebian/apt <distro> Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by cerebrate** [comment]
Unfortunately, I can't seem to repro this, and testing shows the file to be there when I check manually:

```
❯ curl https://arkane-systems.github.io/wsl-transdebian/apt/dists/focal/Release                                                                           
Origin: ArkaneSystems
Label: WSL Transdebian
Codename: focal
Date: Sat, 27 Feb 2021 04:24:46 UTC
Architectures: amd64
Components: main
Description: WSL-specific packages hosted on the Arkane Systems github repository
MD5Sum:
 f5ab0f9415a1b7bc35c0022d859b2e4b 4306 main/binary-amd64/Packages
 b56e6285e25b4a60b3a410785080aca7 1527 main/binary-amd64/Packages.gz
 a2f3caedb64cd6fb7d0cb5f6bed4df32 163 main/binary-amd64/Release
 990bf373dd1341f0b4a16da97034d2d4 2109 main/source/Sources
 42c9f79ff5110651e063d3693d8ba72a 828 main/source/Sources.gz
 d98f5a9c7aeb10035a4016358d9e9454 164 main/source/Release
SHA1:
 243ca3984a270799963674266ae23ba559c6b7f1 4306 main/binary-amd64/Packages
 89d3316be59eadc5c21d2f180133733f85b61f7b 1527 main/binary-amd64/Packages.gz
 d03000dff4b7f7a13deb756cbaa63dcc6f4c9536 163 main/binary-amd64/Release
 7a769e5c71211f3c3c252e02e61a69b4ded5ff50 2109 main/source/Sources
 e956615c209ea0958fc5e6b94b7168299e7f2183 828 main/source/Sources.gz
 48f62b752773af3825c9beeb2c53b2b6987c998b 164 main/source/Release
SHA256:
 c619d248c78bb1d2cf6faceccd2e45332d20f963bd34e6992233c30d4e8b3215 4306 main/binary-amd64/Packages
 f32836dda7eada9ed69b675071ad410c461dfe76fbaa1759ffe3ebbb4322a917 1527 main/binary-amd64/Packages.gz
 c562e878dcc6b169a20988934960aedd1dc7602263b1eb0a06f6d0529afc93c4 163 main/binary-amd64/Release
 71ddfd9f9e856f021a0d26533be9e2bbdef583026db2c5e6af3f93b0fcf354e9 2109 main/source/Sources
 da92ae61e12f416f4a4e018e12e180249bf05accecec46185d1eb489c4db9d90 828 main/source/Sources.gz
 7deaf2f6137cfa9222bcd65d367d7128929a724eb7fb2e1204725eebc41a6171 164 main/source/Release
```

If double-checking your configuration doesn't resolve this, can you try that same curl command and let me know if the output is different?

**Comment by Davikar** [comment]
Yeah, apparently you have to but the actual release name in the source file. It was a while since I worked with Ubuntu... >_<
