### ISSUE TITLE
genie -u fails with message hostname -F /etc/hostname  - file doesn't exists

### ISSUE THREAD

**Issue by PavelSosin-320** [arkane-systems/genie#124]
genie -u files with the message  
genie: error executing command 'hostname -F /etc/hostname':
No such file or directory

Do you mean hostnamectl ???
_[root@MSI-wsl ~]# hostnamectl
 Static hostname: MSI-wsl
       Icon name: computer-container
         Chassis: container
      Machine ID: 051d2c9dfd574a228e61a4776f93258f
         Boot ID: 2844a9d7a8be419f9ab1786e80a0d730
  Virtualization: wsl
Operating System: Fedora 34 (Container Image Prerelease)
     CPE OS Name: cpe:/o:fedoraproject:fedora:34
          Kernel: Linux 5.4.91-microsoft-standard-WSL2
    Architecture: x86-64_
Does it come from the genie or from the distro? systemctl poweroff works better.

**Comment by cerebrate** [comment]
Nope. hostname(1):

https://www.man7.org/linux/man-pages/man1/hostname.1.html

This is your hostname being returned to normal after the `systemctl poweroff`. See https://github.com/arkane-systems/genie/blob/a92aeb2cb1dbbddba12c876ed77823b975c81241/binsrc/genie/Helpers.cs#L147 .

(And hostname(1) is a core utility, so if your distro is missing either it or the /etc/hostname file, something has gone deeply wrong with it somewhere.)

**Comment by PavelSosin-320** [comment]
@cerebrate My distro doesn't contain hostname utility. Maybe, because it is built from RedHat Fedora OCI Container image. As you can guess that RedHat is strongly systemd-oriented and tries to avoid remote access to the container storage at any cost. I have hostnamectl. The hostnamectl (almost) works for me locally and remotely via ssh and it is much more versatile when it comes to the containers, VM's and other "machines". The service etc-hostname is started automatically:
etc-hostname.mount - /etc/hostname
     Loaded: loaded (/proc/self/mountinfo)
     Active: active (mounted) since Mon 2021-03-08 07:43:57 IST; 1h 20min ago
      Where: /etc/hostname
hostnamectl tells me what I need to know about my distro.
 Static hostname: MSI-wsl
       Icon name: computer-container
         Chassis: container
      Machine ID: 051d2c9dfd574a228e61a4776f93258f
         Boot ID: 5f7d7e174e254f22b5e1d81c6fda0d10
  Virtualization: wsl
Operating System: Fedora 34 (Container Image Prerelease)
     CPE OS Name: cpe:/o:fedoraproject:fedora:34
          Kernel: Linux 5.4.91-microsoft-standard-WSL2
    Architecture: x86-64
This is not wrong, this is different.

**Comment by PavelSosin-320** [comment]
After separate hostname package installation dnf install hostname it works as expected. On other hand, hostname is dependency and is not a "organic" part of Machined - MachineCtl, Hostnamed, HostnameCtl, OCI container imageruntimes, ...
For example, wsl ...... genie -u --------> machinectl poweroff VSL distro.
