### ISSUE TITLE
PATH not copied with clone-path=true

### ISSUE THREAD

**Issue by vincent-163** [arkane-systems/genie#135]
Hello. I'm not sure if I made a mistake during configuration, but when I try to run the `code` command inside genie I get the `bash: code: command not found` error.

Here is the output of `echo $PATH`: `/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`

When running WSL without genie I get the full $PATH which includes the VS Code directory so I can run `code` in it. So it's clearly a $PATH problem so modified `/etc/genie.ini` to include the `clone-path=true` option:
```
[genie]
secure-path=/lib/systemd:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
unshare=/usr/bin/unshare
update-hostname=true
clone-path=true
```

However, after shutting down WSL with `wsl --shutdown` and running `wsl genie -s` the full $PATH is still not copied. Did I get anything wrong?

**Comment by vincent-163** [comment]
I found that I was using an older version of genie. After upgrading to the latest version it worked. Sorry for the noise.

**Comment by esgie** [comment]
i have faced similiar issue two times recently on various distros including  Ubuntu.
the behavior was the same regardless of genie version used - path wasn't cloned despite of clone-path set to true.
but meanwhile it worked good on my other distros. With exactly same configuration.
Again, genie was working all fine.
And again, tthe problem was that some other unrelated packets were overriding the PATH - but the tricky part was that it wasn't performed via script placed in profile/bashrc dir or something, but by placing the entry in /etc/environment.
After removing contents of the file, everything went back to normal.

**Comment by SuperSandro2000** [comment]
I fixed this issue with the following snipped in my bashrc:

```bash
# restore Windows PATH
while read -r dir; do
  PATH+=":$(wslupath "$dir")"
done < <(wslvar PATH | tr ';' '\n')
```
