### ISSUE TITLE
nginx - Transport is not connected

### ISSUE THREAD

**Issue by 3kynox** [arkane-systems/genie#136]
Hello,

I'm not sure if it is 'genie' related but when I'm doing any systemctl task with nginx, I've got the error:

```sudo systemctl status nginx.service
Failed to get properties: Transport endpoint is not connected
```

Any idea where that does come from?

Thanks anyway

**Comment by cerebrate** [comment]
Could you give me the output of `env` from a session in which you're experiencing that nginx issue?

**Comment by 3kynox** [comment]
Sure

```
[nox@NoX NoX]$ env
SHELL=/bin/bash
WSL_DISTRO_NAME=Arch
WT_SESSION=7ebeaf78-2cbc-4aca-90b9-cbaed57eeddb
NAME=NoX
PWD=/mnt/c/Users/NoX
LOGNAME=nox
HOME=/home/nox
LANG=en_US.UTF-8
WSL_INTEROP=/run/WSL/8_interop
TERM=xterm-256color
USER=nox
SHLVL=1
WSLENV=WT_SESSION::WT_PROFILE_ID
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/NoX/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/NoX/AppData/Local/Programs/Microsoft VS Code/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
HOSTTYPE=x86_64
WT_PROFILE_ID={a5a97cb8-8961-5535-816d-772efe0c6a3f}
_=/usr/sbin/env
```

**Comment by cerebrate** [comment]
You're not inside the bottle. Remember, `genie -i` just initializes it; you have to enter it using `genie -c` or `genie -s`.

(To expand on that: the genie bottle is like a container, with its own cgroups and separate pid and mount namespaces. Only inside this "container" are you running in the systemd-as-pid-1 world; some systemd-powered things may work to some degree or another outside it, but there's no guarantee anything will, and it's not a supported mode of operation.

You can check whether you're inside the bottle with `genie -b` or by checking for the _INSIDE_GENIE_ environment variable.)

**Comment by 3kynox** [comment]
Thanks a lot, I'm digging a bit more.
