### ISSUE TITLE
clone-path leaves /mnt/c paths out

### ISSUE THREAD

**Issue by aapoalas** [arkane-systems/genie#137]
**Windows version (build number):** Version 1909 (OS Build 18363.1441)

**Linux distribution:** Ubuntu 18.04.5 LTS (Bionic Beaver) from Microsoft Store

**Genie version:** 1.36

**Describe the bug**
I have set genie's clone-path to true and expect `wsl genie -s` to then give me a properly PATH-copied login shell. There seems to be conflicting information in this repo and documentation about whether or not `genie -s` will copy PATH or not but looking at it all I believe that the intention was that `clone-path=true` would copy PATH for `genie -s` as well.

Unfortunately, for some reason on `genie -s` all `/mnt/c` PATH parts are left out.

Here's my PATH from a normal WSL login:
```
username@COMPUTER-wsl:/mnt/c/Users/windowsuser$ echo $PATH
/opt/some/path/current/apps/some-other-path:/opt/some/path/current/apps/yet-another-path:/opt/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/Microsoft.WindowsTerminal_1.6.10571.0_x64__8wekyb3d8bbwe:/mnt/c/Program Files/Common Files/Microsoft Shared/Microsoft Online Services:/mnt/c/Program Files (x86)/Common Files/Microsoft Shared/Microsoft Online Services:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/windowsuser/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/windowsuser/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin
```

And here it is after from a `genie -s` login:
```
username@COMPUTER-wsl:~$ echo $PATH
/opt/some/path/current/apps/some-other-path:/opt/some/path/current/apps/yet-another-path:/opt/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

A bit of checking shows that the PATH is otherwise the same but all of the `/mnt/c` paths have disappeared.

I'm not exactly sure if `genie -c` is keeping the PATH properly either:
```
user@COMPUTER-wsl:/mnt/c/Users/windowsuser$ genie -c echo \$PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```
The few paths at the beginning (those are related to my work) disappear as well.

Here's my genie.ini contents:
```
[genie]
secure-path=/lib/systemd:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
unshare=/usr/bin/unshare
update-hostname=true
clone-path=true
clone-env=WSL_DISTRO_NAME,WSL_INTEROP,WSLENV
systemd-timeout=180
```

**Comment by aapoalas** [comment]
The work-related paths come from `.profile` so those disappearing probably make sense.

**Comment by cerebrate** [comment]
You will indeed not see paths set in `.profile` or other shell profile files when executing commands via `genie -c`, since `genie -c` alone, for efficiency, doesn't execute the following command via a shell, but rather directly. If you need access to things set in the profile while running an individual command in the bottle, you must specify the shell explicitly, viz. `genie -c sh -c <command>`.

**Comment by cerebrate** [comment]
Regarding the primary issue, from within the bottle, could you please let me the have the contents of the `/run/genie.env` and `/run/genie.path` files?

**Comment by aapoalas** [comment]
Here's what I get.
```
username@COMPUTER-wsl:~$ genie -b
inside
username@COMPUTER-wsl:~$ cat /run/genie.env
INSIDE_GENIE=true
WSL_DISTRO_NAME=Ubuntu-18.04
WSLENV=WT_SESSION:BASH_ENV/u:WT_PROFILE_ID
WSL_INTEROP=/run/WSL/7_interop
username@COMPUTER-wsl:~$ cat /run/genie.path
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/Microsoft.WindowsTerminal_1.6.10571.0_x64__8wekyb3d8bbwe:/mnt/c/Program Files/Common Files/Microsoft Shared/Microsoft Online Services:/mnt/c/Program Files (x86)/Common Files/Microsoft Shared/Microsoft Online Services:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/windowsuser/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/windowsuser/AppData/Local/Programs/Microsoft VS Code/binusername@COMPUTER-wsl:~$ echo $PATH
/opt/some/path/current/apps/path:/opt/some/path/current/apps/otherpath:/home/username/.local/bin:/home/username/.deno/bin:/opt/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/chromium-browser:/snap/bin
```

**Comment by cerebrate** [comment]
Hm. Curious.

Well, that's established that `clone-path` is doing its thing, since the full path is being cloned into the `/run/genie.path` file. In theory, what should happen next is that this file should be read and the environment/path set up by the `10-genie-envar.sh` scripts under `/usr/lib/systemd/system-environment-generators` and `/usr/lib/systemd/user-environment-generators`.

To check this step, could you please run `systemctl show-environment` and `systemctl --user show-environment`, and check what PATH contains in the resulting output?

If the `/mnt/c` paths are missing in that output, please then try executing the script manually - i.e., `/usr/lib/systemd/system-environment-generators/10-genie-envar.sh` - and let me know what the output of that is?

**Comment by aapoalas** [comment]
Curious indeed.
```
username@COMPUTER-wsl:~$ systemctl show-environment
LANG=en_US.UTF-8
LANGUAGE=en_US:
PATH=$'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/some/path/platform/current/apps/some-other-path:/some/path/platform/current/apps/yet-another-path:/home/username/.local/bin:/home/username/.deno/bin
INSIDE_GENIE=true
WSLENV=WT_SESSION:BASH_ENV/u:WT_PROFILE_ID
WSL_INTEROP=/run/WSL/7_interop
WSL_DISTRO_NAME=Ubuntu-18.04
DENO_INSTALL=/home/username/.deno
```
That PATH variable doesn't seem proper.
```
username@COMPUTER-wsl:~$ systemctl --user show-environment
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DENO_INSTALL=/home/username/.deno
DOTNET_CLI_TELEMETRY_OPTOUT=1
HOME=/home/username
INSIDE_GENIE=true
LANG=en_US.UTF-8
LANGUAGE=en_US:
LD_LIBRARY_PATH=/opt/some/other/path/current/lib
LOGNAME=username
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/chromium-browser:/snap/bin
SHELL=/bin/bash
USER=username
WSLENV=WT_SESSION:BASH_ENV/u:WT_PROFILE_ID
WSL_DISTRO_NAME=Ubuntu-18.04
WSL_INTEROP=/run/WSL/7_interop
XDG_DATA_DIRS=/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
XDG_RUNTIME_DIR=/run/user/1000
```

The 10-genie-envar.sh seems to be working correctly:
```
username@COMPUTER-wsl:~$ /usr/lib/systemd/system-environment-generators/10-genie-envar.sh
INSIDE_GENIE=true
WSLENV=WT_SESSION:BASH_ENV/u:WT_PROFILE_ID
WSL_INTEROP=/run/WSL/7_interop
WSL_DISTRO_NAME=Ubuntu-18.04
DENO_INSTALL=/home/username/.deno
PATH=/opt/some/other/path/current/apps/some-path:/opt/some/other/path/current/apps/yet-another-path:/home/username/.local/bin:/home/username/.deno/bin:/opt/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/chromium-browser:/snap/bin:/mnt/c/Program Files/WindowsApps/Microsoft.WindowsTerminal_1.6.10571.0_x64__8wekyb3d8bbwe:/mnt/c/Program Files/Common Files/Microsoft Shared/Microsoft Online Services:/mnt/c/Program Files (x86)/Common Files/Microsoft Shared/Microsoft Online Services:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/windowsuser/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/windowsuser/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin
```

So kind of seems like my env is being whacked by something beyond genie, maybe?

**Comment by cerebrate** [comment]
Looks like, yeah.

The most likely thing, it seems to me, is that something else in `/usr/lib/systemd/system-environment-generators` and `/usr/lib/systemd/user-environment-generators` is overwriting the path set by `10-genie-envar.sh`. The environment generators are executed in directory order, newest wins, and running them manually will display what they would add/update in the environment, so it should hopefully be fairly straightforward to isolate the problem one.

(Note: some of them will update PATH with additional directories; that's normal behavior.)

**Comment by PhyX-Meow** [comment]
Exactly same issue here. My Linux distro is Manjaro Linux testing.

**Comment by PhyX-Meow** [comment]
There's another file in my `/usr/lib/systemd/system-environment-generators` folder
After mv it to 05-manjaro, the genie path is successfully copied.
```
❯ cd /usr/lib/systemd/system-environment-generators
❯ /bin/ls
10-genie-envar.sh  10-manjaro
❯ ./10-manjaro
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin
```

**Comment by cerebrate** [comment]
Yeah, no issues on Debian either, where the analogous file is Sir Not Appearing In This Distro.

Right with you on the fix; since genie-envar should preserve the existing PATH, if any, there shouldn't be any harm in bumping it to 80, or so. Added to 1.40.

**Comment by aapoalas** [comment]
Hmm, not sure if this is relevant but:

```
username@COMPUTER-wsl:~$ systemctl --user show-environment
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DOTNET_CLI_TELEMETRY_OPTOUT=1
HOME=/home/username
INSIDE_GENIE=true
LANG=en_US.UTF-8
LANGUAGE=en_US:
LD_LIBRARY_PATH=/opt/valmet/tif/platform/current/lib
LOGNAME=username
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/chromium-browser:/snap/bin
SHELL=/bin/bash
USER=username
WSLENV=WT_SESSION:BASH_ENV/u:WT_PROFILE_ID
WSL_DISTRO_NAME=Ubuntu-18.04
WSL_INTEROP=/run/WSL/7_interop
XDG_DATA_DIRS=/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
XDG_RUNTIME_DIR=/run/user/1000
```

So with the `--user` flag the `systemctl show-environment` command shows the erroneous `/mnt/c/` filtered paths.
