### ISSUE TITLE
Update Documentation for Autostarting `genie`

### ISSUE THREAD

**Issue by adamgranthendry** [arkane-systems/genie#139]
**Is your feature request related to a problem? Please describe.**
`README.md` states "ways to automatically start genie upon entering wsl are available in the repo wiki", but I cannot find this wiki.

**Describe the solution you'd like**
Would be nice if there was a sentence explaining what to add to ~/.bashrc or ~/.zshrc to run initialize genie and run it in shell so this is done automatically on startup of wsl

**Describe alternatives you've considered**
Could it be as simple as adding these lines to the runcom file (e.g. ~.bashrc, ~/.zshrc, ~/.tcsh)?:

```
genie -i > /dev/null &  # initialize genie, discarding output by writing to `/dev/null` and running as daemon in background with `&`
genie -s  # start genie in shell
```

Not sure if I need to add `exec /bin/sh` to the front, or if rather this should go in a `.conf` file instead of runcom.

**Additional context**
Please let me know your thoughts!

**Comment by cerebrate** [comment]
From the front page of the repo/above the README, click the "Wiki" link. That's it. 

You want this page specifically:

https://github.com/arkane-systems/genie/wiki/Automatically-start-genie-on-every-shell-session

**Comment by adamgranthendry** [comment]
@cerebrate Thank you!
