### ISSUE TITLE
Backspaces are misinterpreted in stdin

### ISSUE THREAD

**Issue by hez2010** [arkane-systems/genie#145]
**Windows version (build number):**
21359.1

**Linux distribution:**
Ubuntu focal

**Genie version:**
1.37

**Describe the bug**
Backspaces are misinterpreted in stdin.

**To Reproduce**

Create a cpp source file and compile it to `a.out`:

```cpp
#include<cstdio>
#include<cstring>

int main() {
    char t[1000];
    memset(t, 0, sizeof(t));
    scanf("%s", t);
    printf("%s", t);
    return 0;
}
```

Run `a.out` in genie shell and enter `abc`, then press twice backspace.

You will see the input line becomes `abc\cb`.

**Expected behavior**
The input line should display just `a`.

**Comment by cerebrate** [comment]
This is a Ubuntu-specific issue. For some reason, Ubuntu's initialization process changes the terminal line settings to include echoprt, which is defined as "echo erased characters backward, between '\' and '/'" (per _stty(1)_ man page).

As a workaround, you can clear this with `stty -echoprt` or plain old `stty sane`.

As for a permanent fix, I'm not myself a Ubuntu user and thus don't know where Ubuntu does its tty setup; you're probably better off asking in a Ubuntu-specific forum for that.

**Comment by notpeelz** [comment]
I have the same issue using debian unstable (genie 2.0)
