### ISSUE TITLE
NOTICE: WSLg issues

### ISSUE THREAD

**Issue by cerebrate** [arkane-systems/genie#149]
Yes, there almost certainly will be some.

It was released today. I'm still downloading the update myself. When I have it working, you'll have it working.

Patience, grasshopper.

**Comment by cerebrate** [comment]
Genie for the moment appears to break X connections to the display. There are two causes for this -

1) The three environment variables WSLg uses are not currently preserved by genie. Fixing this is as simple as adding DISPLAY,WAYLAND_DISPLAY,PULSE_SERVER to the clone-env line in /etc/genie.ini; and

2) Most systemd startups clean out the /tmp folder, which unfortunately also nobbles the X server socket. This can be worked around by doing

`sudo mount --bind /mnt/wslg/.X11-unix /tmp/.X11-unix`

.

Proper fixes for these will ship in genie 1.38, which you can expect sometime tomorrow.

**Comment by cerebrate** [comment]
NOTE: Problem 2 affects even WSLg applications running outside the bottle.

**Comment by cerebrate** [comment]
1.38 is out now.

Y'all can go get it; and please now report issues as normal.

**Comment by PhyX-Meow** [comment]
@cerebrate Help please, `/tmp/.X11-unix` is still not mounted in genie v1.40. My Linux distro: Manjaro tesiting

**Comment by PhyX-Meow** [comment]
Oh, manually build v1.41 fix it, sorry for bothering
