### ISSUE TITLE
Cannot install 1.39 on Arch

### ISSUE THREAD

**Issue by rwilliams** [arkane-systems/genie#154]
**Windows version (build number):**
21364.1

**Linux distribution:**
Arch - Installed from Appx https://github.com/yuk7/ArchWSL

**Genie version:**
Currently 1.38, attempting to upgrade to 1.39

**Describe the bug**
When attempting to install 1.39 I get the following error 

```
➜ sudo pacman -U genie-systemd-1.39-1-x86_64.pkg.tar.zst
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) genie-systemd-1.39-1

Total Installed Size:  1.60 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                           [########################################] 100%
(1/1) checking package integrity                                         [########################################] 100%
(1/1) loading package files                                              [########################################] 100%
(1/1) checking for file conflicts                                        [########################################] 100%
error: failed to commit transaction (conflicting files)
genie-systemd: /lib exists in filesystem (owned by filesystem)
Errors occurred, no packages were upgraded.
```

**If the bug involves `systemctl` or a service running under systemd, confirm that you are running inside the bottle:**
The output of `genie -b`.

**To Reproduce**
`sudo pacman -U genie-systemd-1.39-1-x86_64.pkg.tar.zst`

**Expected behavior**
Expect genie to install as normal.

**Additional context**
There is the note about the `wslg-xwayland.socket` for Fedora and Arch users but I'm not sure if that's related.

**Comment by cerebrate** [comment]
Argh. No, that's probably not related, this is just the me-packaging-for-distros-I-don't-use blues.

Try this one?

[genie-systemd-1.39-1-x86_64.pkg.tar.zst.gz](https://github.com/arkane-systems/genie/files/6365324/genie-systemd-1.39-1-x86_64.pkg.tar.zst.gz)

(Extra gzipped for GitHub upload.)

**Comment by rwilliams** [comment]
Good to go! Thanks!

**Comment by cerebrate** [comment]
Great! Sorry for the oops; I'll update the release page.
