### ISSUE TITLE
systemd warning

### ISSUE THREAD

**Issue by gifnksm** [arkane-systems/genie#156]
**Windows version (build number): 20H2 (19042.928)**

Find this by running `Windows 10 Pro 20H2 (19042.928)`

**Linux distribution: Arch Linux**

I use [ArchWSL](https://github.com/yuk7/ArchWSL) to install Arch Linux.

**Genie version:**
The output of `genie --version`

```console
$ genie --version
1.39
```

I use [my custom PKGBUILD](https://github.com/gifnksm/pkgbuild/tree/master/genie-systemd) to install genie.

**Describe the bug**

systemd emits the following warnings

```console
$ genie -b
inside
$ systemctl --version
systemd 248 (248-5-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
$ sudo systemctl daemon-reload
$ systemctl status wslg-xwayland.socket
○ wslg-xwayland.socket
     Loaded: loaded (/usr/lib/systemd/system/wslg-xwayland.socket; enabled; vendor preset: disabled)
     Active: inactive (dead)
   Triggers: ● wslg-xwayland.service
     Listen: /tmp/.X11-unix/X0 (Stream)

 4月 24 11:54:26 surface-wsl systemd[1]: /usr/lib/systemd/system/wslg-xwayland.socket:3: Unknown key name 'Requires' in section 'Socket', ignoring.
 4月 24 11:54:26 surface-wsl systemd[1]: /usr/lib/systemd/system/wslg-xwayland.socket:4: Unknown key name 'After' in section 'Socket', ignoring.
...
```

`Requires=` & `After=` should belong to `Unit` section, not `Socket` section.
see [`systemd.socket(5)`](https://man.archlinux.org/man/systemd.socket.5) and [`systemd.unit(5)`](https://man.archlinux.org/man/systemd.unit.5).

**Comment by cerebrate** [comment]
Oops!

Thanks for catching that. For some reason the warnings didn't show up with my (Debian) systemd...
