### ISSUE TITLE
Env Variables lost on genie -s

### ISSUE THREAD

**Issue by fliespl** [arkane-systems/genie#157]
**Windows version (build number):**
21364

**Linux distribution:**
Ubuntu

**Genie version:**
1.36

**Describe the bug**
Windows introducted WSLG. After logging to genie -s bottle env variablesDISPLAY, WAYLAND_DISPLAY and PULSE_SERVER are being lost.

**Expected behavior**
Env variables should be still available.

Is there any workaround for that?

**Comment by cerebrate** [comment]
WSLg support was introduced in 1.38, improved in 1.39.

(Or you can just add those variables to your clone-env setting, but that doesn't fix the issue with the specific location needed by the X socket, which is why I recommend upgrading to 1.39 instead.)

**Comment by fliespl** [comment]
Thank you - not sure why I missed it (I was pretty sure I run apt update && upgrade...)

Already done it, but found out new failing services now. Should they they be masked or resolved differently?


**user-runtime-dir@123.service**

```
Apr 26 06:44:12 flies-pc-wsl systemd-user-runtime-dir[724]: Failed to remove runtime directory /run/user/123 (after unmounting): Device or resource busy
Apr 26 06:44:12 flies-pc-wsl systemd[1]: user-runtime-dir@123.service: Control process exited, code=exited, status=1/FAILURE
Apr 26 06:44:12 flies-pc-wsl systemd[1]: user-runtime-dir@123.service: Failed with result 'exit-code'.
Apr 26 06:44:12 flies-pc-wsl systemd[1]: Stopped User Runtime Directory /run/user/123.

```

**user@123.service**

`Apr 26 08:29:14 flies-pc-wsl systemd[1]: Starting User Manager for UID 123...
Apr 26 08:29:14 flies-pc-wsl systemd[1860]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Apr 26 08:29:14 flies-pc-wsl systemd[1860]: pam_systemd(systemd-user:session): Runtime directory '/run/user/123' is not owned by UID 123, as it should.
Apr 26 08:29:14 flies-pc-wsl systemd[1860]: pam_systemd(systemd-user:session): Not setting $XDG_RUNTIME_DIR, as the directory is not in order.
Apr 26 08:29:14 flies-pc-wsl systemd[1860]: Trying to run as user instance, but $XDG_RUNTIME_DIR is not set.
Apr 26 08:29:14 flies-pc-wsl systemd[1]: user@123.service: Main process exited, code=exited, status=1/FAILURE
Apr 26 08:29:14 flies-pc-wsl systemd[1]: user@123.service: Failed with result 'exit-code'.
Apr 26 08:29:14 flies-pc-wsl systemd[1]: Failed to start User Manager for UID 123.`



**user@0.service**

```
Apr 26 08:30:24 flies-pc-wsl systemd[1]: Starting User Manager for UID 0...
Apr 26 08:30:24 flies-pc-wsl systemd[1943]: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Apr 26 08:30:24 flies-pc-wsl systemd[1943]: pam_systemd(systemd-user:session): Runtime directory '/run/user/0' is not owned by UID 0, as it should.
Apr 26 08:30:24 flies-pc-wsl systemd[1943]: pam_systemd(systemd-user:session): Not setting $XDG_RUNTIME_DIR, as the directory is not in order.
Apr 26 08:30:24 flies-pc-wsl systemd[1943]: Trying to run as user instance, but $XDG_RUNTIME_DIR is not set.
Apr 26 08:30:24 flies-pc-wsl systemd[1]: user@0.service: Main process exited, code=exited, status=1/FAILURE
Apr 26 08:30:24 flies-pc-wsl systemd[1]: user@0.service: Failed with result 'exit-code'.
Apr 26 08:30:24 flies-pc-wsl systemd[1]: Failed to start User Manager for UID 0.
```

**Comment by cerebrate** [comment]
Actually, no, this may be an issue with the manner in which WSLg can be conveniently supported.

First, it raises a number of interesting questions, starting with some along the lines of "what's your regular user's uid?", "gdm?", and "why are there three user sessions all running at once, and is it intentional?"

**Comment by cerebrate** [comment]
Most importantly, do you run any GUI applications under real-UIDs other than 1000?

**Comment by fliespl** [comment]
My regular uid is 1000.
GDM is 123.

Nope - three sessions are not intentional - this fails right after starting WSL from regular (1000) user.

**Comment by cerebrate** [comment]
I was meaning more in the sense that GDM (in the sense of the Gnome Display Manager and its handling of graphical logins) isn't supported under WSL/WSLg, so far as I know, because WSLg just projects individual Wayland/X11 applications and doesn't support running a full Gnome/etc. desktop. I'm guessing trying to fire up GDM is what's causing the issue, by virtue of spawning those extra user sessions under UIDs 123 and 0.

I'm going to look at hacking a solution into genie's WSLg support to deal with different-UID user sessions just to be on the safe side, but my speculation right now is that disabling or uninstalling GDM will fix your issue.

**Comment by cerebrate** [comment]
(Unless you don't have GDM installed, in which case, um. Well. Something's firing up those extra sessions, and I'm not sure what it might be. Time to go digging.)

**Comment by fliespl** [comment]
Thanks - will look later today what dependency installed GDM.

Gonna let you know about results I am able to pin-point root cause.

**Comment by fliespl** [comment]
I think it was PHPStorm IDE, which required me to install such packages to work correctly:

```
- apt:
    state: present
    name:
      - libxss1
      - libnss3-dev
      - libgdk-pixbuf2.0-dev
      - libgtk-3-dev
      - libxss-dev
      - libgbm-dev
      - libxkbcommon-dev
      - libatk1.0-dev
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libnotify-dev
      - libgconf-2-4
      - libnss3
      - libasound2
      - libgstreamer-plugins-bad1.0-0
      - libenchant1c2a
      - gstreamer1.0-libav
```

**Comment by cerebrate** [comment]
Hm, looks like. Does the IDE still work if you uninstall gdm3? The other libraries and so forth should be fine.

**Comment by cerebrate** [comment]
There'll also be a fix for other sessions trying to bind wslg/runtime-dir shipping in 1.40, later today.

**Comment by fliespl** [comment]
Yeap, it works after uninstalling gdm3. It's really messy that it's being installed while not required at all - thanks!

**Comment by cerebrate** [comment]
Shiny. Thanks for letting me know.
