### ISSUE TITLE
Support for hirsute / Broken WSLg in 1.40

### ISSUE THREAD

**Issue by fliespl** [arkane-systems/genie#161]
I am aware it's not supported just yet (or at all)

**Is your feature request related to a problem? Please describe.**
I have installed focal release into hirsute and almost everything works perfectly. The only issue I am having is that on start `/tmp/.X11-Unix` is not mounted correctly to ` /mnt/wslg/.X11-unix` as it is on ubuntu focal (20.04). Suspecting that some systemd script behaves differently or are being run in wrong order.

**Describe the solution you'd like**
Probably small fix to support Ubuntu hirsute 21.04. Haven't noticed any other issues. After symlinking correctly:
```
sudo rm -rf /tmp/.X11-unix/
sudo ln -sf /mnt/wslg/.X11-unix /tmp/
```

Everything looks good. So there is probably some minor difference in systemd scripts between both distributions.

**Comment by fliespl** [comment]
Actually - just noticed that it also fails on ubuntu 20.04 with version 1.40 - didn't have this problem with 1.39.

**Comment by fliespl** [comment]
Pinpointed the issue to:

ConditionVirtualization=microsoft

inside wslg-xwayland.service & socket.

**Comment by cerebrate** [comment]
....huh.

What do you get from `systemd-detect-virt` on that system?

**Comment by fliespl** [comment]
```
root@flies-pc-wsl:/mnt/e/Dropbox/Web-Devel/Tools/wsl/ansible-os# systemd-detect-virt
wsl
root@flies-pc-wsl:/mnt/e/Dropbox/Web-Devel/Tools/wsl/ansible-os# systemd-detect-virt --container
wsl
root@flies-pc-wsl:/mnt/e/Dropbox/Web-Devel/Tools/wsl/ansible-os# systemd-detect-virt --vm
microsoft
```

**Comment by cerebrate** [comment]
Hm. Must be a newer version of systemd. What's your `systemd --version`?

**Comment by fliespl** [comment]
In 20.04 (where it also failed with 1.40):
```
$ systemd --version
systemd 245 (245.4-4ubuntu3.6)
```

In 21.04:
```
$ systemd --version
systemd 247 (247.3-3ubuntu3)
```

**Comment by cerebrate** [comment]
Well, now. That's strange, insofar as I'm also on 247 (247.3-5):

```
❯ systemd-detect-virt
microsoft

❯ systemd-detect-virt --vm
microsoft

❯ systemd-detect-virt --container
none
```

**Comment by fliespl** [comment]
Is it possible that it's not store image of WSL? But normal rootfs ubuntu 20.04 image?

Maybe it's based on /etc/os-release?

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by fliespl** [comment]
Also uname -a output:

```
# uname -a
Linux flies-pc-wsl 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cerebrate** [comment]
Hm. Time to go digging into the systemd source, I think.

**Comment by fliespl** [comment]
That's what I found in the meantime:

```
        /* "Official" way of detecting WSL https://github.com/Microsoft/WSL/issues/423#issuecomment-221627364 */
        r = read_one_line_file("/proc/sys/kernel/osrelease", &o);
        if (r < 0)
                log_debug_errno(r, "Failed to read /proc/sys/kernel/osrelease, ignoring: %m");
        else if (strstr(o, "Microsoft") || strstr(o, "WSL")) {
                r = VIRTUALIZATION_WSL;
                goto finish;
        }
```

and virtualization_wsl is declared as "wsl" and not microsoft.

**Comment by cerebrate** [comment]
Ah, that's it, then. Case sensitivity, despite the way that tools various tend to bitch if you use uppercase in the kernel version string. I do so love consistency...

Will be fixed in 1.41.

**Comment by fliespl** [comment]
Thanks and amazing work as always! :)

Gonna let you know if I run into anymore issues with 20.04 or 21.04 during 1.41 testing.

**Comment by cerebrate** [comment]
Actually - here's a 1.41 prelim if you want to get a head start on that! 😁 

[systemd-genie_1.41_amd64.deb.gz](https://github.com/arkane-systems/genie/files/6423290/systemd-genie_1.41_amd64.deb.gz)

**Comment by fliespl** [comment]
And it works perfectly! Great job!

**Comment by cerebrate** [comment]
Actually, just to lampshade the problem behind this problem:

The chief problem here is that if you try to build a _packaged_ custom kernel with an osrelease string that matches the "official" criteria, you can't. Because this:

```
dpkg-buildpackage -r"fakeroot -u" -a$(cat debian/arch)  -i.git -us -uc
dpkg-buildpackage: info: source package linux-5.10.16.3-20210504-1-microsoft-custom-WSL2+
dpkg-buildpackage: info: source version 5.10.16.3-20210504-1-microsoft-custom-WSL2+-2
dpkg-buildpackage: info: source distribution bullseye
dpkg-buildpackage: info: source changed by Alistair Young <avatar@arkane-systems.net>
 dpkg-source -i.git --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-source: error: source package name 'linux-5.10.16.3-20210504-1-microsoft-custom-WSL2+' is illegal: character 'W' not allowed
dpkg-buildpackage: error: dpkg-source -i.git --before-build . subprocess returned exit status 255
make[1]: *** [scripts/Makefile.package:77: deb-pkg] Error 255
make: *** [Makefile:1529: deb-pkg] Error 2
zsh: exit 2
```

...so, that's helpful. 'Scuse me while I go off and drop a rhetorical bomb on some folks.

**Comment by fliespl** [comment]
Probably something that should be brought to wsl2 developers attention?

**Comment by cerebrate** [comment]
Just the folks I'm talking about!

**Comment by cerebrate** [comment]
Reported over at https://github.com/microsoft/WSL/issues/6911 .
