### ISSUE TITLE
Cannot start genie after upgrading to 1.4

### ISSUE THREAD

**Issue by bitbocs** [arkane-systems/genie#17]
After upgrading to 1.4 cannot start genie, output I get is:

> bogdan@bogdan-PC /c/Users/bogdan $ genie -s --verbose
> genie: no bottle present.
> genie: initializing bottle.
> Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: No such file or directory
>    at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
>    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start(String fileName, String arguments)
>    at ArkaneSystems.WindowsSubsystemForLinux.Genie.Program.InitializeBottle(Boolean verbose)
>    at ArkaneSystems.WindowsSubsystemForLinux.Genie.Program.ShellHandler(Boolean verbose)
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Delegate.DynamicInvokeImpl(Object[] args)
>    at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
>    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass2_0.<<InvokeAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseErrorReporting>b__16_0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass8_0.<<UseTypoCorrections>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseDebugDirective>b__4_0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__14_0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass3_0.<<UseVersionOption>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__17_0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass5_0.<<UseExceptionHandler>b__0>d.MoveNext()

I'm using Windows 10 Pro Insider Preview, build 18970.1005, WSL 2 Ubuntu 18.04.

**Comment by cerebrate** [comment]
Could I ask you to upgrade to the (just released) 1.5 and give it another try? I'm afraid it probably won't fix the problem itself, but it should at least reveal the exact location of the issue.

Thanks.

**Comment by bitbocs** [comment]
Apparently, my configuration doesn't have chmod located in /usr/bin, is in /bin (My distribution was upgraded from WSL 1 to WSL 2, if it helps).

Here's the output:

> bogdan@bogdan-PC /c/Users/bogdan $ genie -s --verbose
genie: no bottle present.
genie: initializing bottle.
genie: error executing command '/usr/bin/chmod 644 /etc/hostname-wsl':
No such file or directory
bogdan@bogdan-PC /c/Users/bogdan $ ls -al /etc/hostname-wsl
-rw-r--r-- 1 root root 14 Sep  4 16:43 /etc/hostname-wsl
bogdan@bogdan-PC /c/Users/bogdan $ which chmod
/bin/chmod
>

**Comment by cerebrate** [comment]
Glad you found a workaround. I'll eliminate the need for that chmod call in the next release.
