### ISSUE TITLE
Idea for running VS Code inside genie bottle

### ISSUE THREAD

**Issue by vincent-163** [arkane-systems/genie#172]
**UPDATE**: The VS Code is now asking for the community to vote. 10 votes are needed within 60 days to make the feature request into their backlog. Please vote at https://github.com/microsoft/vscode-remote-release/issues/5145 if this feature helps you!

This is mainly a memo for myself but I hope it would be useful to someone else.

VS Code for WSL always spawnes the server using `wsl` command, and therefore the VS Code server is always outside the bottle. This makes it hard to interact with systemd and make processes created by VS Code visible to processes inside the bottle.

I've submitted an issue to VS Code repository: https://github.com/microsoft/vscode-remote-release/issues/5145

Meanwhile, I found a hack to make VS Code server run inside the bottle, by prepending the following lines to `%USERPROFILE%\.vscode\extensions\:ms-vscode-remote.remote-wsl-*\scripts\`:
```bash
# Check if inside bottle
if ! genie -b > /dev/null; then
        # Rerun current script inside bottle
        exec genie -c "$0" "$@"
fi
```

Would you like to include the solution somewhere in the documentation?

**Comment by cerebrate** [comment]
The wiki here should be publicly editable. Feel free to add it there.

**Comment by PavelSosin-320** [comment]
@vincent-163 Only for clarification: do you mean the "native" vscode server from 
![NativeVSCodeForLinux](https://user-images.githubusercontent.com/54495912/120916826-6c667900-c6b4-11eb-8086-1e018acd8c44.png) or starting Win VSCode from WSL? In the 1st case, it's necessary to calculate VSCode dependencies like Network target, workspace mount,  .... to ensure smooth vscode server startup.

**Comment by cerebrate** [comment]
@vincent-163 You may also want to make that first line:

```
if ! genie -b > /dev/null; then
```

to avoid unwanted console output when starting VS Code from inside WSL.

**Comment by vincent-163** [comment]
> @vincent-163 You may also want to make that first line:
> 
> ```
> if ! genie -b > /dev/null; then
> ```
> 
> to avoid unwanted console output when starting VS Code from inside WSL.

Thanks for the suggestion. I've edited the code.

The VS Code issue linked above is now asking for the community to vote. 10 votes are needed within 60 days to make the feature request into their backlog. Please vote if this feature helps you!

**Comment by InTheKeyOfCSharp** [comment]
Should this issue be closed now? It seems that the linked issue (https://github.com/microsoft/vscode-remote-release/issues/5145) got into the backlog and that a wiki page has been added for this troubleshooting.

**Comment by cerebrate** [comment]
Since it's open-ended, I leave that up to the original poster, just in case something else comes up. (Of, if not, the bot will get it.)
