### ISSUE TITLE
Ubuntu can't satisfy dotnet-runtime-5.0 package dependency (package doesn't exist, and isn't recognized after Microsoft.com install procedure)

### ISSUE THREAD

**Issue by mick-p1982** [arkane-systems/genie#176]
I've installed ".Net" this (https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install) way for lack of any other way. This doesn't seem to register it with the package system for purposes of resolving the dependency on the systemd-genie package.

```
michael@Nova:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

```
michael@Nova:~$ sudo apt install -y systemd-genie
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 systemd-genie : Depends: dotnet-runtime-5.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

EDITED: Note, suspiciously (and apart from package resolution) the command "dotnet" doesn't work (dotnet --list-sdks) even though the following:

```
michael@Nova:~$ sudo ./dotnet-install.sh -c 5.0 --runtime aspnetcore
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Downloading primary link https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/5.0.7/aspnetcore-runtime-5.0.7-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/5.0.7/aspnetcore-runtime-5.0.7-linux-x64.tar.gz
dotnet-install: Adding to current process PATH: `/root/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
michael@Nova:~$ ./dotnet-install.sh -c 5.0
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Downloading primary link https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0.301/dotnet-sdk-5.0.301-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0.301/dotnet-sdk-5.0.301-linux-x64.tar.gz
dotnet-install: Adding to current process PATH: `/home/michael/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
```

Maybe Microsoft is to blame here, I don't know. (I'm probably to blame, but seeing as how there's no straightforward way to install .Net more explicit instructions would be welcome.)

**Comment by ShinyCoconut** [comment]
Having the same problem here. The command `dotnet` even works, but the package does not get recognized as installed.

**Comment by cerebrate** [comment]
The scripted install is not supported with genie (for reasons as described in the scrpt output above) precisely because it doesn't register the runtime with the package management system. Only the apt-based install - https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu - is supported.

You may be able to make a script-based install work by faking the presence of the package with some tool like _equivs_ , but I can't support such a setup.

**Comment by ShinyCoconut** [comment]
> The scripted install is not supported with genie (for reasons as described in the scrpt output above) precisely because it doesn't register the runtime with the package management system. Only the apt-based install - https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu - is supported.
> 
> You may be able to make a script-based install work by faking the presence of the package with some tool like _equivs_ , but I can't support such a setup.

I have done what you said and it worked, glad for the attention, thanks for the project 🥰

**Comment by mick-p1982** [comment]
@ShinyCoconut Thanks, this helped me to get further along to. If I missed a recommendation to not use the script option before I apologize. (I think I'm probably still stuck though going by my results post-install. I've copied them below in case @cerebrate cares to comment.)

```
Waiting for systemd....!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Timed out waiting for systemd to enter running state.
This may indicate a systemd configuration error.
Attempting to continue.
Failed units will now be displayed (systemctl list-units --failed):
  UNIT                       LOAD   ACTIVE SUB    DESCRIPTION
● multipathd.service         loaded failed failed Device-Mapper Multipath Device Controller
● systemd-remount-fs.service loaded failed failed Remount Root and Kernel File Systems
● multipathd.socket          loaded failed failed multipathd control socket
LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
3 loaded units listed.
```

**Comment by cerebrate** [comment]
I would comment that I created this wiki page in this very repo, describing these specific issues among others:

https://github.com/arkane-systems/genie/wiki/Systemd-units-known-to-be-problematic-under-WSL

...so that I would not _have_ to comment.

**Comment by ShinyCoconut** [comment]
> @ShinyCoconut Thanks, this helped me to get further along too. If I missed a recommendation to not use the script option before I apologize. (I think I'm probably still stuck though going by my results post-install. I've copied them below in case @cerebrate cares to comment.)
> 
> ```
> Waiting for systemd....!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> Timed out waiting for systemd to enter running state.
> This may indicate a systemd configuration error.
> Attempting to continue.
> Failed units will now be displayed (systemctl list-units --failed):
>   UNIT                       LOAD   ACTIVE SUB    DESCRIPTION
> ● multipathd.service         loaded failed failed Device-Mapper Multipath Device Controller
> ● systemd-remount-fs.service loaded failed failed Remount Root and Kernel File Systems
> ● multipathd.socket          loaded failed failed multipathd control socket
> LOAD   = Reflects whether the unit definition was properly loaded.
> ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
> SUB    = The low-level unit activation state, values depend on unit type.
> 3 loaded units listed.
> ```
When it happens with me, I simply run "systemctl disable **service_name**" for each of the services listed, and then run genie again.
