### ISSUE TITLE
Sudo apt update is failing due to repo being unsigned and/or having unverified signatures

### ISSUE THREAD

**Issue by helgatheviking** [arkane-systems/genie#178]
**Windows version (build number):**
Windows 10 dev build 21390.2025 (using WSL 2)

**Linux distribution:**
Ubuntu 20.04

**Genie version:**
n/a

**Describe the bug**
I've followed the instructions [here](https://arkane-systems.github.io/wsl-transdebian/#configuring-the-wsl-transdebian-repo) to add the repo for this project. But I cannot run the `sudo apt install -y systemd-genie` command. That returns `E: Unable to locate package systemd-genie`.

`sudo apt update` displays errors about the repo being unsigned:

```
W: GPG error: https://arkane-systems.github.io/wsl-transdebian/apt focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 428AD1A0BA078ABB
E: The repository 'https://arkane-systems.github.io/wsl-transdebian/apt focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

So I tried the `--allow-unauthenticated` flag

`sudo apt update --allow-unauthenticated`

and still get a notice about not being able to update as the signature can't be verified:

```
Err:2 https://arkane-systems.github.io/wsl-transdebian/apt focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 428AD1A0BA078ABB
Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
W: GPG error: https://arkane-systems.github.io/wsl-transdebian/apt focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 428AD1A0BA078ABB
E: The repository 'https://arkane-systems.github.io/wsl-transdebian/apt focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Expected behavior**
`sudo apt update` fetches packages from the wsl-transdebian repo

I don't know if this is actually a bug or if I need support with Ubuntu...

**Comment by cerebrate** [comment]
I can't repro this, but what it looks like is that the public key for the repo isn't installed on your system. If the install steps for the repo were carried out correctly, you should have that key in `/etc/apt/trusted.gpg.d/wsl-transdebian.gpg` - can you confirm whether or not this file exists? Also, if the file is correct, it should have an MD5 checksum of `a1fbd2fc46e6f9332fae1f12f4524dbf`, and the following key:

```
/etc/apt/trusted.gpg.d/wsl-transdebian.gpg
------------------------------------------
pub   rsa4096 2021-01-19 [SC]
      43BE 3332 3EDD 7126 03BE  E6C0 428A D1A0 BA07 8ABB
uid           [ unknown] WSL Transdebian Repo Signing Key <arkane@arkane-systems.net>
sub   rsa4096 2021-01-19 [E]
```

should show up among the other results from `apt-file list`.

If any or all of these things aren't the case, I suggest repeating the first lines (to set up the key) of the install procedure, viz.:

```
wget -O /etc/apt/trusted.gpg.d/wsl-transdebian.gpg https://arkane-systems.github.io/wsl-transdebian/apt/wsl-transdebian.gpg

chmod a+r /etc/apt/trusted.gpg.d/wsl-transdebian.gpg
```

inside a `sudo -s` session, and send me any errors that occur during it.

**Comment by helgatheviking** [comment]
Thank you for reply! I think I might have made a mistake.... After re-reading your reply I got it to work. I was not correctly in elevated user mode.
