### ISSUE TITLE
'bindxsocket.sh' does not exist when try to build

### ISSUE THREAD

**Issue by frankli998** [arkane-systems/genie#181]
**Windows version (build number):**
22000.100

**Linux distribution:**
Debian from Microsoft store
Opensuse Tumbleweed

**Genie version:**
1.38

**Describe the bug**
`install: cannot stat 'othersrc/scripts/bindxsocket.sh': No such file or directory`

**To Reproduce**
run `sudo make install-local`

**Comment by cerebrate** [comment]
1.38 is an older version (the bindxsocket.sh script was replaced in later releases).  Any particular reason you're trying to use 1.38 instead of the current release?

**Comment by cerebrate** [comment]
Aside from that, if you check manually, does the othersrc/scripts/bindxsocket.sh file exist after cloning the repo and switching to the 1.38 tag using `git checkout tags/v1.38`? Has the othersrc symlink been created correctly in the package/local subdirectory?

**Comment by frankli998** [comment]
By the time the bug was reported, version is 1.38. Newer version not released. I will check newest version and feedback

**Comment by frankli998** [comment]
The bug still exist. In Make file there is one line `install -Dm 0755 -o root "othersrc/scripts/bindxsocket.sh" -t "$(INSTALLDIR)"`
I think it is the root of this bug

**Comment by frankli998** [comment]
> Aside from that, if you check manually, does the othersrc/scripts/bindxsocket.sh file exist after cloning the repo and switching to the 1.38 tag using `git checkout tags/v1.38`? Has the othersrc symlink been created correctly in the package/local subdirectory?

Yes, bindsocket.sh exists

**Comment by frankli998** [comment]
> The bug still exist in version 1.46. In `genie/package/local/Makefile` there is one line `install -Dm 0755 -o root "othersrc/scripts/bindxsocket.sh" -t "$(INSTALLDIR)"`
> I think it is the root of this bug

**Comment by cerebrate** [comment]
Ah, oops. In 1.43/1.44, that's definitely a bug since they don't use that script. Edit that line out of the Makefile, and that version should work.

**Comment by frankli998** [comment]
fixed. Tested on newest OpenSUSE Tumbleweed.
