### ISSUE TITLE
Cannot install 1.43 on Arch

### ISSUE THREAD

**Issue by nabobalis** [arkane-systems/genie#183]
Just wanted to say thank you for providing this package!

This seems to be a reoccurrence of https://github.com/arkane-systems/genie/issues/154 but with the latest version.

 **Windows version (build number):**
Version	10.0.22000 Build 22000 (I am on W11)
 
 **Linux distribution:**
 Arch - Installed from Arch.zip [yuk7/ArchWSL](https://github.com/yuk7/ArchWSL)
 
 **Genie version:**
 Currently 1.42, attempting to upgrade to 1.43
 
 **Describe the bug**
 When attempting to install 1.43 I get the following error
 
 ```
❯ sudo pacman -U genie-systemd-1.43-1-x86_64.pkg.tar.zst
[sudo] password for nabil:
loading packages...
resolving dependencies...
looking for conflicting packages...

Package (1)    Old Version  New Version  Net Change

genie-systemd  1.42-1       1.43-1         0.00 MiB

Total Installed Size:  1.95 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                           [########################################] 100%
(1/1) checking package integrity                                         [########################################] 100%
(1/1) loading package files                                              [########################################] 100%
(1/1) checking for file conflicts                                        [########################################] 100%
error: failed to commit transaction (conflicting files)
genie-systemd: /lib exists in filesystem (owned by filesystem)
Errors occurred, no packages were upgraded.
```
 
 **If the bug involves `systemctl` or a service running under systemd, confirm that you are running inside the bottle:**
 The output of `genie -b`.
 
 **To Reproduce**
 `sudo pacman -U genie-systemd-1.43-1-x86_64.pkg.tar.zst`
 
 **Expected behavior**
 Expect genie to install as normal.
 
 **Additional context**

**Comment by cerebrate** [comment]
Gah. Try this one?

[genie-systemd-1.43-1-x86_64.pkg.tar.zst.gz](https://github.com/arkane-systems/genie/files/6907915/genie-systemd-1.43-1-x86_64.pkg.tar.zst.gz)

gzipped on top of the zst so I can include it here.

**Comment by nabobalis** [comment]
That installed for me.

**Comment by cerebrate** [comment]
Great! I'll swap out the file in the release.
