### ISSUE TITLE
1.44 genie: must execute as root - has the setuid bit gone astray

### ISSUE THREAD

**Issue by kylhuk** [arkane-systems/genie#194]
**Windows version (build number):**
21H1

**Linux distribution:**
Ubuntu 20.04 LTS

**Genie version:**
1.44

**Describe the bug**
Constantly got `genie: must execute as root - has the setuid bit gone astray`.
The uid was set correctly. Installed it as `.deb` package.

1.43 installed from source works fine.

**Comment by cerebrate** [comment]
Unfortunately, I can't repro this on my Ubuntu 2.04 install.

As well as the uid/gid being root, can you confirm that the setuid bit is set on the `/usr/libexec/genie/genie` file?

**Comment by kylhuk** [comment]
I've just tested it on another Ubuntu 20.04 installation, where I just upgraded to 1.44 with `apt` and I can't reproduce this neither.

And as I can see, the `setuid` is correctly set in the `.deb` package. Will test again soon and update.

**Comment by kylhuk** [comment]
Installed it again with the pre-built `.deb` package. Can't reproduce it anymore. So I'll close this issue for now.

**Comment by codylane** [comment]
FWIW - I just had this happen to me today on Ubuntu 20.04 in WSL using systemd-genie=1.44.  I got the very same error message and fixed the problem by doing the following inside my Ubuntu 20.04 terminal.

```
chown root:root /usr/libexec/genie/genie
chmod 4755 /usr/libexec/genie/genie
```
