### ISSUE TITLE
Random Arkane error on WSL start

### ISSUE THREAD

**Issue by fliespl** [arkane-systems/genie#198]
**Windows version (build number):**
1903

**Linux distribution:**
ubuntu 20.04

**Genie version:**
1.44

**Describe the bug**
Randomly I am experiencing this error on starting WSL. It mentions arkane, so I guess must be related.

I haven't been able to find root cause why it sometimes happens. Ideas?

Using resolved-stub=true

**Screenshots**
https://ss.codeone.pl/ss-2021-09-01-09-15-52-1630480552-Y7dMjeoZ.png

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [x] Yes.

**Comment by fliespl** [comment]
Some more info:
- my wsl is setup to start using task scheduler as follows

```
$taskName = "Start WSL"

$user = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name

Unregister-ScheduledTask -TaskName $taskName -Confirm:$false


$action = New-ScheduledTaskAction -Execute 'Powershell.exe' -Argument '-NoProfile -NoExit -file "E:\Dropbox\wsl\ansible-os\ps\start_wsl.ps1"'
$trigger = New-ScheduledTaskTrigger -AtLogon -User $user

Register-ScheduledTask -RunLevel Highest -Action $action -Trigger $trigger -User $user -TaskName $taskName -Description $taskName
```

and start_wsl.ps1 simply does:

`wsl -e bash -c "genie -i"`

**Comment by cerebrate** [comment]
This may be a performance-related problem.

If you're still having the issue, does it ever occur when you manually start WSL a sufficient time after logon that the system has settled down to idle?
