### ISSUE TITLE
Add CentOS/EL support?

### ISSUE THREAD

**Issue by ancienter** [arkane-systems/genie#204]
I usually use CentOS/EL to work, but it's a pity that I can't use systemd.Maybe many people are like me, so adding CentOS/El support may be a good idea

**Comment by cerebrate** [comment]
In theory, at least, the .rpm package from the releases page should work on CentOS and other .rpm-using distros, or at least should be able to be made to work, as should a local installation.

Unfortunately, I have neither the time nor the experience to properly maintain and test a CentOS-specific package myself, so I'm rather left hoping for someone to come along interested in taking the role of CentOS maintainer.
