### ISSUE TITLE
[doc help] confused about doc of update-hostname option

### ISSUE THREAD

**Issue by roachsinai** [arkane-systems/genie#213]
Related doc is:

> The update-hostname setting controls whether or not genie updates the WSL hostname when creating the bottle. By default, genie updates a hostname foo to foo-wsl, to prevent hostname clashes between the host Windows machine and the WSL distribution, especially when communicating back and forth between the two. However, as recent Insider builds allow the hostname of the WSL distributions to be set in .wslconfig, this option has been provided to disable genie's intervention and keep the original hostname.

So I wanna know make sure whether once you run `genie -i` the hostname will change to foo-wsl?

For my situation the answer is yes:

```
owin-wsl ~ » pstree
systemd─┬─2*[agetty]
        ├─crond
        ├─dbus-daemon
        ├─systemd───(sd-pam)
        ├─systemd-journal
        ├─systemd-logind
        ├─systemd-machine
        ├─systemd-socket-
        ├─systemd-udevd
        └─zsh─┬─(sd-pam)
              └─pstree
owin-wsl ~ » exit

owin-wsl /tmp » pstree
init─┬─init───init─┬─unshare───systemd─┬─2*[agetty]
     │             │                   ├─crond
     │             │                   ├─dbus-daemon
     │             │                   ├─systemd───(sd-pam)
     │             │                   ├─systemd-journal
     │             │                   ├─systemd-logind
     │             │                   ├─systemd-machine
     │             │                   ├─systemd-socket-
     │             │                   └─systemd-udevd
     │             └─zsh
     ├─init───init───zsh───zsh───vim─┬─python3───2*[{python3}]
     │                               └─7*[{vim}]
     ├─init───init───zsh
     ├─init───init───zsh───pstree
     └─2*[{init}]
owin-wsl /tmp »
```

The hostname is both owin-wsl even not in a genie shll.

Thanks!

**Comment by cerebrate** [comment]
If the update-hostname setting is true, the hostname will change when genie is initialized, yes.

The hostname will change both inside and outside the bottle because inside and outside share a UTS namespace (per https://man7.org/linux/man-pages/man7/namespaces.7.html ). Only mount and PID namespaces are separate.
