### ISSUE TITLE
Crashing on .NET 6.0.0

### ISSUE THREAD

**Issue by julianxhokaxhiu** [arkane-systems/genie#215]
**Windows version (build number):**
10.0.19043.1348

**Linux distribution:**
Arch Linux ( ArchWSL )

**Genie version:**
```sh
$ genie --version
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=arch-x64
```

**Describe the bug**
Arch has updated its dotnet-runtime package to 6.0.0 and this broke Genie which expects to find a dotnet-runtime v5.0.0.

Can you please release an updated version as .NET 6.0 was released officially for all Linux distributions too?

**Confirm that you are running inside the bottle:**
```sh
$ genie -b
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=arch-x6
```

**To Reproduce**
1. Open your WSL bash.exe session
2. Run `genie --version`
3. See error

**Expected behavior**
Genie runs successfully.

**Screenshots**
N/A

**Additional context**
N/A

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [x] Yes.

**Comment by julianxhokaxhiu** [comment]
As a workaround I've installed this AUR package, which allows `genie` to run again: https://aur.archlinux.org/packages/dotnet-runtime-5.0-bin/

**Comment by ongyx** [comment]
Yep, I can confirm that `dotnet-host`, `dotnet-runtime`, and `dotnet-sdk` were recently upgraded to .NET 6.0 in the main repos. Until genie can be built using .NET 6.0, I'll change the PKGBUILD dependencies to use the aforementioned .NET 5.0 packages for now.

**Comment by Postroggy** [comment]
> As a workaround I've installed this AUR package, which allows `genie` to run again: [aur.archlinux.org/packages/dotnet-runtime-5.0-bin](https://aur.archlinux.org/packages/dotnet-runtime-5.0-bin/)

Thx， bro. I finally made it.

**Comment by cerebrate** [comment]
I have altered the Arch build to specify .NET version required explicitly to prevent a recurrence.
