### ISSUE TITLE
daemonize not found after installing systemd-genie, but genie can't run daemonize. 

### ISSUE THREAD

**Issue by 12nick12** [arkane-systems/genie#217]
Kind of a weird issue. If I install daemonize I can run it, but once I install systemd-genie daemonize is not found which genie seems to require. 

I'm on Windows 11

**Comment by cerebrate** [comment]
What is the path to your daemonize (`which daemonize`)?

**Comment by 12nick12** [comment]
I ended up needing to install daemonize from source. After I installed systemd-genie daemonize was no longer a valid command.
