### ISSUE TITLE
Flag to disable the "-wsl" hostname suffix

### ISSUE THREAD

**Issue by rtm516** [arkane-systems/genie#219]
**Is your feature request related to a problem? Please describe.**
Currently, when entering the bottle the hostname gets prefixed with "-wsl"

**Describe the solution you'd like**
A flag or some other way of disabling the suffix being added.

**Describe alternatives you've considered**
None

**Additional context**
[UpdateHostname function](https://github.com/arkane-systems/genie/blob/670803c3864cfe28d8eaea2c5dbb79d7740210f5/binsrc/genie/Helpers.cs#L94)

**Comment by rtm516** [comment]
Looking at this more, for my use case, it is something I've decided to keep. But others would likely still appreciate the option.

**Comment by skvskv** [comment]
@rtm516 did you try setting empty hostname suffix in the ini config file? If yes, then how exactly did you do that and what was the result?

**Comment by cerebrate** [comment]
Added in 1.45.
