### ISSUE TITLE
Errors starting genie

### ISSUE THREAD

**Issue by dylanmeca** [arkane-systems/genie#236]
**Windows version (build number):**
Windows 11 SO 22000.527

**Linux distribution:**
Ubuntu 20.04.4 focal

**Genie version:**
genie 2.0

**Describe the bug**
When I run genie -s to start it, it takes a long time to start and I get error messages, and those messages are:

genie: systemd did not enter running state (degraded) after 60 seconds
genie: this may be due to a problem with your systemd configuration
genie: information on problematic units is available at https://github.com/arkane-systems/genie/wiki/Systemd-units-known-to-be-problematic-under-WSL

genie: WARNING: systemd is in degraded state, issues may occur!

I don't know how to solve it, but I can't understand the wiki documentation, because I don't know much about linux configurations and it's the first time I see these errors, could you help me to solve my error, please. I had to modify systemd-timeout to avoid waiting too long.

**Confirm that you are running inside the bottle:**
inside

**To Reproduce**
1. Install genie according to this website: https://arkane-systems.github.io/wsl-transdebian/
2. systemctl set-default multi-user.target
3. genie -s
4. I finally get those error messages

**Expected behavior**
I expected everything to work properly with no errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/55631040/156857314-1bde15b8-1882-4132-b159-dcf4cef5c878.png)
![image](https://user-images.githubusercontent.com/55631040/156857473-26102f3f-1a2e-4067-914a-f7306b88c946.png)

**Additional context**
I forgot to mention that when I run ```systemctl apache2 status``` I get the message: Unknown operation apache2. And that I have apache2 installed, I don't know why this would happen.

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [*] Yes.

**Comment by dylanmeca** [comment]
yes, I had made a mistake when writing the command

**Comment by cerebrate** [comment]
@akuropka has covered the apache issues (the other service evidently running on port 80).

The other two units are known to be problematic. As per the README, see here for instructions on how to correct these issues:

https://github.com/arkane-systems/genie/wiki/Systemd-units-known-to-be-problematic-under-WSL
