### ISSUE TITLE
`genie -c` fails with paths containing spaces

### ISSUE THREAD

**Issue by notpeelz** [arkane-systems/genie#240]
**Windows version (build number):**
Windows 10 Pro 21H2 (OS Build 19044.1526)

**Linux distribution:**
Debian unstable (sid)

**Genie version:**
`genie --version`: `2.0`
`apt-cache show systemd-genie`: `2.2`

**Describe the bug**
After applying the patch mentioned [here](https://github.com/arkane-systems/genie/wiki/Running-VS-Code-server-for-WSL-inside-genie-bottle), the VS Code server fails to launch:
![image](https://user-images.githubusercontent.com/920910/157000712-4777d679-a87d-4ac9-94fd-d88fde3c5027.png)

In the screenshot above, you can see `runinwsl` failing to locate `/mnt/c/Users/peelz/AppData/Local/Programs/Microsoft VS Code` (cut off at the first space)

I managed to fix the issue by changing this line:
```diff
--- a/binsrc/genie/__main__.py
+++ b/binsrc/genie/__main__.py
@@ -660,7 +660,7 @@ def do_command(commandline):
     command = ["machinectl", "shell", "-q", login + "@.host", "/usr/lib/genie/runinwsl", os.getcwd()] + commandline

     with nsenter.Namespace (sdp, 'pid'):
-        sp = subprocess.run (' '.join(command), shell=True)
+        sp = subprocess.run (command)
         return sp
```

**Extra information**
The [`command` array](https://github.com/arkane-systems/genie/blob/c560e8a79e2390975893b7226fd03a278fabeb8c/binsrc/genie/__main__.py#L660) contains this:
```
['machinectl', 'shell', '-q', 'peelz@.host', '/usr/lib/genie/runinwsl', '/mnt/c/Users/peelz/AppData/Local/Programs/Microsoft VS Code', '/mnt/c/Users/peelz/.vscode/extensions/ms-vscode-remote.remote-wsl-0.64.2/scripts/wslServer.sh', 'b5205cc8eb4fbaa726835538cd82372cc0222d43', 'stable', 'code-server', '.vscode-server', '--host=127.0.0.1', '--port=0', '--connection-token=3502240250-2084421065', '--use-host-proxy', '--without-browser-env-var', '--disable-websocket-compression', '--accept-server-license-terms']
```

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [X] Yes.

**Comment by cerebrate** [comment]
Fixed in 2.3. Thanks for the catch.
