### ISSUE TITLE
systemd keeps running after exiting the wsl distro.

### ISSUE THREAD

**Issue by akuropka** [arkane-systems/genie#245]
**Windows version (build number):**
10.0.22572.100

**Linux distribution:**
Arch Linux using [wsldl](https://github.com/yuk7/wsldl).

**Genie version:**
genie 2.0 (as per `genie --version`)
genie 42e1d851b333a8292c4f84aba8e87eda3891f305 (actually built version)

**Describe the bug**
With genie initialized and running as shell (`genie -s`) after exiting the session with `exit` the shell window keeps open and does not close automatically.

**Confirm that you are running inside the bottle:**
`inside`

**Command used during starting the shell session (e.g. .bash_profile):**
```
# Start genie
if [[ ! -v INSIDE_GENIE ]]; then
  exec /usr/bin/genie -s
fi
```
**To Reproduce**
1. Add above code to `.bash_profile`.
2. For safety's sake shut down wsl (`wsl --shutdown`).
3. Open a new shell.
4. `exit` the shell.

**Expected behavior**
The shell window closes.

**Screenshots**
![20220314_115539_wslhost](https://user-images.githubusercontent.com/22570574/158158615-376e040b-803b-4a65-83be-73d50f888872.png)

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**
 - [X] Yes.

**Comment by cerebrate** [comment]
Haven't had any luck reproing this so far, alas.

A couple of questions, though --

- If you start a shell in an existing command prompt window using `genie -s`, does it return to the command prompt on exit?
- Does this happen on second or subsequent (simultaneous) shell windows, or only the first one?

**Comment by akuropka** [comment]
@cerebrate, thank you for your reply.
Please see the screencast, maybe you have an idea... it's only after running genie.

https://user-images.githubusercontent.com/22570574/159068907-f38575a9-3514-46d3-8d7d-9217dbd61bc2.mp4

**Comment by cerebrate** [comment]
Huh. That is very strange.

My best speculation here is that there has to be some leftover process in the session keeping the pty alive and so holding the window open. So I've got to ask you for three more things:

- the output of `ps aux` before running genie -s
- the output of `systemctl status` inside the bottle
- the output of `ps aux` after exiting the bottle

Hopefully that'll give us a clue as to what it might be.

**Comment by akuropka** [comment]
ps aux before entering the bottle:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.1  0.0   2020  1280 ?        Sl   18:32   0:00 /init
root        14  0.0  0.0   2028    96 ?        Ss   18:32   0:00 /init
root        15  0.1  0.0   2028   104 ?        S    18:32   0:00 /init
andi        16  0.2  0.0   8604  5228 pts/0    Ss   18:32   0:00 -bash
andi       131  0.0  0.0  10220  3356 pts/0    R+   18:32   0:00 ps aux
```
systemctl status inside bottle:
```
● ANDI-wsl
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Sat 2022-03-19 18:32:15 CET; 7s ago
   CGroup: /
```
ps aux after exiting the bottle:
```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   2020  1280 ?        Sl   18:32   0:00 /init
root          14  0.0  0.0   2028    96 ?        Ss   18:32   0:00 /init
root          15  0.1  0.0   2028   104 ?        S    18:32   0:00 /init
andi          16  0.1  0.0   8604  5292 pts/0    Ss   18:32   0:00 -bash
root         140  0.0  0.0   5640  1028 ?        Ss   18:32   0:00 /usr/sbin/unshare -fp --propagation shared --mount-proc -- systemd
root         141  2.2  0.0  21676 11560 ?        Ss   18:32   0:00 systemd
root         168  3.6  0.1  56660 29268 ?        Ss   18:32   0:00 /usr/lib/systemd/systemd-journald
root         177  0.7  0.0  27252  8252 ?        Ss   18:32   0:00 /usr/lib/systemd/systemd-udevd
dbus         201  0.1  0.0   8596  4884 ?        Ss   18:32   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root         202  0.2  0.0  15736  7648 ?        Ss   18:32   0:00 /usr/lib/systemd/systemd-logind
root         204  0.0  0.0   5656  1048 hvc0     Ss+  18:32   0:00 /sbin/agetty -o -p -- \u --keep-baud 115200,57600,38400,9600 - vt220
root         208  0.0  0.0  15448  7416 ?        Ss   18:32   0:00 /usr/lib/systemd/systemd-machined
andi         214  0.3  0.0  17484 10144 ?        Ss   18:32   0:00 /usr/lib/systemd/systemd --user
andi         215  0.0  0.0  25128  2880 ?        S    18:32   0:00 (sd-pam)
andi         345  0.0  0.0  10220  3436 pts/0    R+   18:32   0:00 ps aux
```

**Comment by akuropka** [comment]
I'm closing this as it seems the issue cannot be resolved.
In addition I moved to a different solution.
