### ISSUE TITLE
genie shell stops (bottle already established, could not initialize)

### ISSUE THREAD

**Issue by akuropka** [arkane-systems/genie#248]
**Windows version (build number):**
10.0.22572.201

**Linux distribution:**
Arch Linux using [wsldl](https://github.com/yuk7/wsldl).

**Genie version:**
2.3 (https://github.com/arkane-systems/genie/commit/3b50b85bb562c01b622fe590e2a6f2329aa1fb08)

**Describe the bug**
I'm trying to run genie initialized as shell (`genie -s`) but it exits
```
Waiting for systemd....!
genie: bottle is already established (systemd running)
could not initialize bottle, exit code = 1
```
However, subsequent windows do open, genie is running.

**Confirm that you are running inside the bottle:**
`inside`

**Command used during starting the shell session (e.g. .bash_profile):**
```
# Start genie
if [[ ! -v INSIDE_GENIE ]]; then
  exec /usr/bin/genie -s
fi
```

**To Reproduce**
1. Add above code to` .bash_profile`.
2. For safety's sake shut down wsl (`wsl --shutdown`).
3. Open a new shell.
4. Open another shell window.

**Expected behavior**
System does not stop running in the initial window.

**Screencast**
https://user-images.githubusercontent.com/22570574/159068065-b3c4e788-c4e1-4620-9ccb-78a89d6f72a4.mp4

**Additional context**
Downgrade to c176e711f4456466853cd89bd581053ec9679cb1 is a workaround.

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**
 - [X] Yes.

**Comment by cerebrate** [comment]
Caused by an editor glitch; fix already made but hadn't been pushed yet. It is now.
