### ISSUE TITLE
Python 3.9.2 Exception (Debian)

### ISSUE THREAD

**Issue by Coalmine-Canary** [arkane-systems/genie#249]
**Windows version (build number):**
Version 21H2 (OS Build 19044.1586)

**Linux distribution:**
Debian 11.2

**Genie version:**
Can't run genie, but the version shown by apt is: 2.2

**Describe the bug**
Python index error using Python version 3.9.2

**Confirm that you are running inside the bottle:**
N/A

**To Reproduce**
1. Install Debian from the Microsoft store
2. Follow instructions to add wsl-transdebian apt repo (https://arkane-systems.github.io/wsl-transdebian/)
3. apt install systemd-genie
4. Run any genie command

**Expected behavior**
The outcome of the genie command. 

**Screenshots**
![image](https://user-images.githubusercontent.com/52761451/159117104-65b772be-72e5-4ef1-85b1-61857443b714.png)

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [X] Yes.

**Comment by xITmasterx** [comment]
Same problem here.

**Comment by cerebrate** [comment]
This is probably #243 , which will be fixed in 2.3. But just in case it isn't, can you both confirm that you are running genie on a WSL 2 distro (`wsl -l -v`) and, if you are, send me the output of `mount` from that distro?

**Comment by xITmasterx** [comment]
I am dumb, It's still on WSL1. Forgot to update it to 2. Sorry about that.
Here's the mount info:
![ubuntu_CYwKzOhJGI](https://user-images.githubusercontent.com/69068829/159131208-a4376a47-e87c-4631-ad7a-154766d96161.png)
As well as the wls 2 distro check:
![powershell_hW1x7Oix5R](https://user-images.githubusercontent.com/69068829/159131227-03241dfa-c512-40fb-a87b-7a157e3c12b1.png)
Also, How do I fix this?
![ubuntu_GByw1bWoWP](https://user-images.githubusercontent.com/69068829/159131177-e8c59110-523c-4f89-bf34-daecd97d8370.png)

**Comment by Coalmine-Canary** [comment]
@cerebrate Thanks for responding so quickly, I made the same mistake as xITmasterx. I've just upgraded to WSL2 and it's all working correctly now.

**Comment by cerebrate** [comment]
Closing, as fix is in 2.3.
