### ISSUE TITLE
Genie on Rocky gives Python errors

### ISSUE THREAD

**Issue by bighead85** [arkane-systems/genie#254]
**Windows version (build number):**
Windows 11 buld 22000.556 

**Linux distribution:**
Rocky from https://docs.rockylinux.org/guides/interoperability/rocky_to_wsl_howto/ 

**Kernel version:**
5.10.60.1-microsoft-standard-WSL2

**Genie version:**
genie 2.3

**Describe the bug**
From $genie -i -v
genie: starting systemd with command line:
daemonize /usr/bin/unshare -fp --propagation shared --mount-proc -- systemd
Waiting for systemd....Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/genie/genie/__main__.py", line 904, in <module>
  File "/usr/lib/genie/genie/__main__.py", line 887, in entrypoint
  File "/usr/lib/genie/genie/__main__.py", line 656, in do_initialize
  File "/usr/lib/genie/genie/__main__.py", line 196, in get_systemd_state
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

Cannot find any details on this error in previous issues so unsure how to tackle, using python 3.6.8 and installed from the RPM release.

**To Reproduce**
genie -s fails
because of this genie -b shows outside.

**Comment by cerebrate** [comment]
Oops. Sorry, this looks to be a limitation in the current RPM packaging, which I'll fix in the next release - you need python 3.7 or greater to run genie. 3.6 hadn't implemented the `capture_output` parameter to `subprocess.run()` yet.

If you can update your python, that should fix the problem.

**Comment by bighead85** [comment]
perfect thank you, updated python manuall to 3.7 and working now. Appreciate you looking!
