### ISSUE TITLE
after daemonize upgrade to 1.7.8-1(using apt)genie cannot work now.

### ISSUE THREAD

**Issue by HawkShell** [arkane-systems/genie#257]
**Windows version (build number):**
Find this by running `winver`
Windows 11 Ver 22H2 (22581.100)
**Linux distribution:**
i.e. Debian bullseye, Ubuntu focal, etc.
If your distro was not installed from the Microsoft Store, please indicate source and method of installation.
Ubuntu Devel
**Kernel version:**
The output of `cat /proc/sys/kernel/osrelease`
5.10.102.1
**Genie version:**
The output of `genie --version`
1.31
**Describe the bug**
run: 
genie -s
or
genie -i
show:
daemonize: illegal option -- f
Bad option: -f
genie: initializing bottle failed; daemonize returned 139.

**Confirm that you are running inside the bottle:**
The output of `genie -b`.
'-b' was not matched. Did you mean '-v', or '-i', or '-s', or '-l', or '-c', or '-u', or '-h'?
Unrecognized command or argument '-b'

genie:
  Handles transitions to the "bottle" namespace for systemd under WSL.

Usage:
  genie [options] [command]

Options:
  -v, --verbose     Display verbose progress messages [default: False]
  --version         Show version information
  -?, -h, --help    Show help and usage information

Commands:
  -i, --initialize           Initialize the bottle (if necessary) only.
  -s, --shell                Initialize the bottle (if necessary), and run a shell in it.
  -l, --login                Initialize the bottle (if necessary), and open a logon prompt in it.
  -c, --command <command>    Initialize the bottle (if necessary), and run the specified command in it.
  -u, --shutdown             Shut down systemd and exit the bottle.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [ ] Yes.

**Comment by cerebrate** [comment]
1.31 is a _very_ obsolete version of genie.

Can you reproduce this on the current release (2.3)?

**Comment by cerebrate** [comment]
Closed as stale.
