### ISSUE TITLE
wsl mount not working as expected after installing genie

### ISSUE THREAD

**Issue by mwoodpatrick** [arkane-systems/genie#259]
**Windows version (build number):**
Windows 11 Insider Preview 22593.1 (ni_release)

**Linux distribution:**
Ubuntu 20.04.4 LTS (Focal Fossa)

**Kernel version:**
5.10.102.1-microsoft-standard-WSL2

**Genie version:**
genie 2.3

**Describe the bug**
wsl mount not working as expected (this used to work before installing genie)

**Confirm that you are running inside the bottle:**
The output of `genie -b` is 'no-bottle' but I do see a set of init processes running I'm confused as to how genie gets run at wsl startup I would like to control this explicitly but have checked my wsl.conf file and don't see where this is being done. I will continue to search the docs and my system 

F S UID        PID  PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
**4 S root         1     0  0  80   0 -   508 -      03:16 ?        00:00:00 /init**
5 S root       123     1  0  80   0 -   507 -      03:16 ?        00:00:00 /init
5 S root       124   123  0  80   0 -   507 -      03:16 ?        00:00:00 /init
4 S root       125   124  0  80   0 - 401671 -     03:16 pts/0    00:00:00 /mnt/wsl/docker-desktop/docker-desktop-user-d
5 S root       137   123  0  80   0 -   507 -      03:16 ?        00:00:00 /init
4 S mwoodpa+   138   137  0  80   0 - 191196 futex_ 03:16 pts/1   00:00:01 docker serve --address unix:///home/mwoodpatr
5 S root       152     1  0  80   0 -   507 -      03:18 ?        00:00:00 /init
5 S root       153   152  0  80   0 -   507 -      03:18 ?        00:00:00 /init
4 S mwoodpa+   154   153  0  80   0 -  3510 do_wai 03:18 pts/2    00:00:00 -bash
5 S root       895     1  0  80   0 -   507 -      05:04 ?        00:00:00 /init
5 S root       896   895  0  80   0 -   507 -      05:04 ?        00:00:00 /init
4 S mwoodpa+   897   896  0  80   0 -  3510 core_s 05:04 pts/3    00:00:00 -bash
0 R mwoodpa+  2998   154  0  80   0 -  2654 -      07:10 pts/2    00:00:00 ps -Alf

**To Reproduce**

Running

wsl.exe -d Alpine mount --bind /home/mwoodpatrick/projects /mnt/wsl/projects

gives error:

`<3>init: (8) ERROR: CreateProcessParseCommon:749: Failed to translate \\wsl.localhost\Ubuntu\home\mwoodpatrick`

and does not mount in expected location, actually mounts in  /home/mwoodpatrick/projects
**Expected behavior**
Should mount the volume in /mnt/wsl/projects

**Screenshots**

**Additional context**

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [ x] Yes.

**Comment by akuropka** [comment]
The `/init` is the original wsl one, if the bottle is running PID 1 would be `systemd`.
[Usage](https://github.com/arkane-systems/genie#usage) explains how to use genie and enter the bootle (systemd environment), there's nothing written to `wsl.conf` by default.

What I noticed is that you want to run the mount command in `Alpine` but the error refers to `Ubuntu`.

**Comment by 3axap4eHko** [comment]
@mwoodpatrick  Do I understand correctly that you are trying to mount the `/home/mwoodpatrick/projects` directory into `/mnt/wsl/projects` directory?

**Comment by cerebrate** [comment]
Apart from @akuropka 's comment above (you aren't actually running _genie_ ; it must be started explicitly as explained in the README for this repo), I can't reproduce any issues using _wsl --mount_ with _genie_. Please open a new issue if you have this problem when running under genie.
