### ISSUE TITLE
Windows 11 + Genie 2.3: Genie seems stuck

### ISSUE THREAD

**Issue by jmauro** [arkane-systems/genie#266]
**Windows version (build number):**
Version 21h2 (OS build 22000.652)

**Linux distribution:**
```
$ cat /etc/debian_version
bookworm/sid
```

**Kernel version:**
```
$ cat /proc/sys/kernel/osrelease
5.10.102.1-microsoft-standard-WSL2
```

**Genie version:**
```
$ genie -V
genie 2.3
```

**Describe the bug**
When launching any `genie` command, the system is still waiting systemd to start
```
$ genie -vvv -s
genie: starting shell
genie: starting bottle
genie: generating new hostname
genie: external hostname is Thinkpad-vhdx
genie: setting new hostname to Thinkpad-vhdx-wsl
genie: updating hosts file
genie: unmounting binfmt_misc filesystem before proceeding
genie: AppArmor not available in kernel; attempting to continue without AppArmor namespace
genie: starting systemd with command line:
daemonize /usr/bin/unshare -fp --propagation shared --mount-proc -- systemd
Waiting for systemd............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```
**Confirm that you are running inside the bottle:**
N/A

**To Reproduce**
Each time I am launching `genie`

**Expected behavior**

**Screenshots**

**Additional context**
Even when changing the timeout value, the waiting time is way way too long:
```
$ cat /etc/genie.ini
[genie]
systemd-timeout=60
clone-env=WSL_DISTRO_NAME,WSL_INTEROP,WSLENV,DISPLAY,WAYLAND_DISPLAY,PULSE_SERVER
secure-path=/lib/systemd:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
clone-path=false
target-warning=true
update-hostname=true
update-hostname-suffix=-wsl
resolved-stub=false
```
![image](https://user-images.githubusercontent.com/1178356/166559441-4a0b3857-d0db-49bd-b084-8097bbe5bbe5.png)

 - [ ] Yes.

**Comment by jmauro** [comment]
Ok I found the issue and this is not linked to `systemd-genie` but

**Comment by PaulKGrimes** [comment]
Hi Jmauro - please could you explain where this is controlled, and what it should be set to?  I'm having the same issue with a fresh Rocky-Linux wsl install.

**Comment by jmauro** [comment]
Hello,

I have set up in the `.wslconfig` the boot command line to use, so I put the `systemd.unified_cgroup_hierarchy=1`

**Comment by jmauro** [comment]
Hello, 
Sorry for the lack of context.

**Comment by PaulKGrimes** [comment]
> Hello, Sorry for the lack of context.

No problem. As you can see from my edit, I figured it out, and left some extra documentation for future users.
