### ISSUE TITLE
What benefits or new features does your script provide compared to what is implemented in ubuntu-22.04?

### ISSUE THREAD

**Issue by haosmos** [arkane-systems/genie#273]
It's not really a request for new functionality, I just don't know in what category to put this question — because it's not a description of the bug either)

I'm sorry, maybe I'm asking the wrong question. I'm looking for an option to run wsl using systemd. While looking for a solution, I found your script. Apparently it works well.

But I have a question. I installed wsl ubuntu-22.04 and created a file /etc/wsl.conf where I specified this setting:

```
[boot]
command="/usr/libexec/wsl-systemd"
```

After that, the wsl runs apparently from under systemd:

![WindowsTerminal_Ift7Jvrq6t](https://user-images.githubusercontent.com/30666874/171034174-b617e4b0-bdc4-4d18-bb03-967cda2738cd.png)

I have accessed the services via systemctl and can manage them:

![WindowsTerminal_pCNsTS5Py5](https://user-images.githubusercontent.com/30666874/171019115-b62c8f1a-1bbd-4d26-91e3-48aa5c290eb0.png)

Only 2 services remained unactivated:

![WindowsTerminal_s4YKA9A4JM](https://user-images.githubusercontent.com/30666874/171019229-c50e0656-23ae-4d68-9027-05951d6afb92.png)

But I took the advice you pointed out in your wiki and after making these settings, namely, after I commented out the line in the /etc/fstab file:

```
#LABEL=cloudimg-rootfs   /        ext4   discard,errors=remount-ro       0 1
``` 

and edited the /usr/lib/systemd/system/systemd-sysusers.service as follows:

```
[Unit]
Description=Create System Users
Documentation=man:sysusers.d(5) man:systemd-sysusers.service(8)
DefaultDependencies=no
Conflicts=shutdown.target
After=systemd-remount-fs.service
Before=sysinit.target shutdown.target systemd-update-done.service
ConditionNeedsUpdate=/etc

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=systemd-sysusers
TimeoutSec=90

[Service]
LoadCredential=

#Optionally, pick up a root password and shell for the root user from a

#credential passed to the service manager. This is useful for importing this
#LoadCredential=passwd.hashed-password.root
#LoadCredential=passwd.plaintext-password.root
#LoadCredential=passwd.shell.root
```

Then these services are working:

![WindowsTerminal_P9ADoVnDvi](https://user-images.githubusercontent.com/30666874/171034299-3cc46f01-b6c0-40d5-863d-842a807bd316.png)

One important thing: I specified the path to wsl in windows terminal like this:

C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu22.04LTS_2204.0.9.0_x64__79rhkp1fndgsc\ubuntu2204.exe

If you set it like this: wsl.exe -d Ubuntu-22.04, it will not run under systemd for some reason.

It seems to work: I can open folders via: 

```
explorer.exe .  
```
and files in wsl using vscode via:

```
code . 
```

I can also download and install snap packages:

![WindowsTerminal_y0z1oiwD2V](https://user-images.githubusercontent.com/30666874/171035006-63273c51-4f32-48fe-b0af-2a6cbca503ca.png)

My question is: what benefits or new features does your script provide compared to what is implemented in ubuntu-22.04?

And how can I check the limitations of the systemd startup mechanism implemented in ubuntu-22.04? Maybe your script works better?

**Comment by cerebrate** [comment]
Do they officially support this (systemd) in Jammy? At first glance, it looks like they hacked this script together so they could run their desktop installer, which comes in the form of a snap, rather than for general use.

Anyway, I can see a few differences already, but I'll take some time to go through their code and let you know what I find.

**Comment by cerebrate** [comment]
Yeah, definitely looks on the hackish side. Here's the quick list of things you get from using genie:

- AppArmor support
- Automatic (optional) stub setup for systemd-resolved
- Hostname fixup to avoid clashes when using bridged networking
- /etc/hosts automatically updated as above
- Status-fetching options (inside/outside, running/not-running)
- /tmp cleaned up by systemd, then automatically restored
- User-friendly interface for commands/shells/login

...also documentation and error handling.

Also, how are you getting into the systemd namespace once this has started? Do all new sessions you start end up in there? I'm not seeing anything in the code to make that happen.

**Comment by haosmos** [comment]
I did some experiments with my wsl. 

I installed the native Docker for linux on - without Docker Desktop for Windows - so far everything seems to work fine: the docker service runs when the system is aging and I can manage docker with systemctl. 

![WindowsTerminal_2YLqWqss1R](https://user-images.githubusercontent.com/30666874/172050830-8d3f33da-8181-4e9c-8522-c4560eeaa7ff.png)

I can also create and run containers. I connected to a container via phpstorm installed in windows via ssh. I couldn't figure out how to connect to the container in wsl via phpstorm directly, so I connected via ssh. I can also manage containers through the phpstorm interface. 

![L3PFPLgfWA](https://user-images.githubusercontent.com/30666874/172050856-0c26b190-4dd8-445e-a543-0288b8c68fc4.png)

I also have no problem installing and can run postgres inside wsl and connect to it via phpstorm. I can also manage postgres via systemctl. 

![phpstorm64_oAVEuXZFFa](https://user-images.githubusercontent.com/30666874/172050803-3614be39-e3b8-436c-87ac-3b9dff74df81.png)

![WindowsTerminal_AzWpRQC1ZZ](https://user-images.githubusercontent.com/30666874/172066635-2bdc9ffc-55cb-4e21-9ba6-11e9e596387d.png)

All in all, so far, everything seems to be working without problems and everything looks like I'm working with normal linux. 
How can I figure out if there are any problems or limitations with the way my system works now? Maybe there is some kind of test?
 
Maybe your script gives some advantages over what I have now?

**Comment by msh2050** [comment]
Can I do the same for fedora distro?
It is better to add this to documentation

**Comment by cerebrate** [comment]
When it comes down to it, I'm afraid, I simply don't have the time to do comparative testing against and/or advising regards the three? - four now, given that it's possible to do this with the Ubuntu install script - assorted ways to get systemd running involving other tools and distros than mine.

If what you're using works for you, that's great, but I can't advise further.
