### ISSUE TITLE
Genie fails to start

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [arkane-systems/genie#28]
Just ran through the installation process as per the README file, and ran the following command and received the following error.
```
> wsl genie -s
/sbin/runuser: invalid option -- 'w'
Try 'runuser --help' for more information.
```
I am using an Insider Build, with Build number 18999.vb_release.191004-1432, running Ubuntu 18.04.3 in WSL 2.

When I run genie in WSL, I also get the following output after what was also returned above:
```
genie: starting shell failed; nsenter returned 1.
```

**Comment by HeyITGuyFixIt** [comment]
Added `-v`:
```
$ sudo genie -s -v                                                                                                                                        genie: outside bottle 4154.                                                                                                                                                   genie: starting shell                                                                                                                                                         envar: INSIDE_GENIE=true                                                                                                                                                      envar: WSL_DISTRO_NAME=                                                                                                                                                       envar: WSL_INTEROP=                                                                                                                                                           envar: WSLENV=                                                                                                                                                                /sbin/runuser: invalid option -- 'w'                                                                                                                                          Try 'runuser --help' for more information.                                                                                                                                    genie: starting shell failed; nsenter returned 1. 
```

**Comment by cerebrate** [comment]
Hm. Just to eliminate the obvious, could you give me the output from `sudo runuser --help` ? Specifically, we're looking for this line:

```
 -w, --whitelist-environment <list>  don't reset specified variables
```

Also, the version information given by `sudo runuser -V`.

Thanks.

**Comment by HeyITGuyFixIt** [comment]
I had previously looked at the output of `sudo runuser --help` and didn't see it. I've also been doing a little research and found out that 18.04 doesn't have the w option in their version of runuser ([man page](http://manpages.ubuntu.com/manpages/bionic/man1/runuser.1.html)).

19.04 does, however. I had upgraded to 19.04 to see if that fixes it, which is does. But that means that I can't give you the information you need, unless I figure out a way to have two versions of Ubuntu running side by side. I'll try to set it up like that, and if you have any advice on getting it done, that would be very helpful.

**Comment by cerebrate** [comment]
Thanks for investigating this. I don't have a convenient fix for it, unfortunately, so I'll document the workaround in the README.
