### ISSUE TITLE
logrotate.service fails

### ISSUE THREAD

**Issue by Mukul1127** [arkane-systems/genie#293]
**Windows version (build number):**
19044.1826

**Linux distribution:**
Ubuntu Preview - MS Store

**Kernel version:**
5.18.0-rc1-next-20220405-microsoft-cbl - Custom Kernel From https://github.com/nathanchance/wsl2-linux-kernel

**Genie version:**
genie 2.4

**Describe the bug**
```
$ systemctl --failed
  UNIT              LOAD   ACTIVE SUB    DESCRIPTION
* logrotate.service loaded failed failed Rotate log files

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
1 loaded units listed.
```
Every once and a while logrotate.service fails

**Confirm that you are running inside the bottle:**
inside

**To Reproduce**
Unsure - Appears Randomly

**Expected behavior**
No Failed Systemd Units

**Screenshots**
None

**Additional context**
I normally do `wsl --shutdown` and then start Ubuntu again, but I want a real fix pls.

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [x] Yes.

**Comment by cerebrate** [comment]
This is probably something in the logrotate config for your system, not a general _genie_ error. My recent similar issue was caused by a permissions issue on the ceph log, for example. In any case, `systemctl status logrotate` should give you more detailed information on the problem.

**Comment by Mukul1127** [comment]
thanks
