### ISSUE TITLE
Failed to detect WSL2 instance

### ISSUE THREAD

**Issue by jacky9813** [arkane-systems/genie#298]
**Windows version (build number):**
`Windows 10 Pro Version 21H2 (Build 19044.1889)`

**Linux distribution:**
`Debian Bullseye`, upgraded from `Debian Stretch` from Microsoft Store

**Kernel version:**
`5.10.16.3-microsoft-standard-WSL2`

**Genie version:**
The output of the command is `genie: not executing under WSL 2 - how did we get here?`
The command `sudo apt list | grep genie` shows it's `2.4 amd64`

**Describe the bug**
As the output of the version shows, genie is unable to detect that the environment is running WSL2.

**Confirm that you are running inside the bottle:**
Negative.

**To Reproduce**
1. Follows the [instruction](https://arkane-systems.github.io/wsl-transdebian/) and install `systemd-genie`.
2. Shutdown the WSL2 with `wsl.exe --shutdown`
3. Try Starting WSL2 with `wsl.exe genie -s`, the error occurs.

**Expected behavior**
Launches WSL2 with systemd and opens a shell prompt.

**Screenshots**
![image](https://user-images.githubusercontent.com/13483393/191656275-a8f56396-e430-48b8-b7af-3a382acaf7a0.png)

**Additional context**
Workaround:
Using command `wsl.exe sudo touch /run/WSL ; genie -s`

==================

The message appears to be generated `genie: not executing under WSL 2 - how did we get here?` in line 71 of file [binsrc/genie/helpers.py](https://github.com/arkane-systems/genie/blob/master/binsrc/genie/helpers.py#L71)
Here's a snippet of it:
```python
    if not os.path.exists('/run/WSL'):
        if 'microsoft' not in os.uname():
            sys.exit("genie: not executing under WSL 2 - how did we get here?")
```

The function [os.uname](https://docs.python.org/3/library/os.html#os.uname) will return a structured named attributes.
Hence the checking the output of uname against `'microsoft'` will never be `True`.

Thus I recommend using `os.uname().release` instead: 
```python
    if not os.path.exists('/run/WSL'):
        if 'microsoft' not in os.uname().release:
            sys.exit("genie: not executing under WSL 2 - how did we get here?")
```

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [x] Yes.

**Comment by cerebrate** [comment]
schrödinbugs are the weirdest, inasmuch as this has been working elsewhere for some time despite the fact that it shouldn't.

🤷🏻‍♂️ 

Still, fixed in 2.5.
