### ISSUE TITLE
Missing dll with .NET Core version

### ISSUE THREAD

**Issue by niklas88** [arkane-systems/genie#3]
Trying to install from the new release I'm getting the following error
```
user@xyz /tmp/genie-1.2 % sudo cp * /usr/local/bin
user@xyz /tmp/genie-1.2 % genie -s
A fatal error occurred, the required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/usr/local/bin/].
If this is a framework-dependent application, install the runtime in the default location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.
```
I guess .NET Core can't produce binaries which only depend on libc like it's the default for e.g. Go?

**Comment by niklas88** [comment]
More information: I tested on Ubuntu 18.04.x fully updated. The python version worked for me.

**Comment by cerebrate** [comment]
Yep, that's the missing-runtime error. Per the README, you need to install the runtime with the instructions here for it to work: https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/runtime-current .

(It "sort of" can; that's the self-contained application option, but that does it by essentially including the whole runtime library as individual dependencies, which is to say, many, many files. There are ways - a third-party tool now, and in .NET Core 3.0, currently in preview - to pack this into a single binary, but that relies on exploding the files back into a cache on first run, and gives you a 30MB binary. That's even worse than the python single-file executable, which converts 4.7KB of script into 4.5MB, vs. the .NET Core version's 156KB compiled. The separate runtime is bigger, but it's also shared.

So looking at those options, I went with taking the dependency.)
