### ISSUE TITLE
wsl genie -s and wsl genie -c bash hang

### ISSUE THREAD

**Issue by Erfboom** [arkane-systems/genie#30]
You guessed it, I'm running Arch. I arrived at genie from the Arch WSL git and managed to install genie, but it hangs no matter what option is used at "Adding hostname-wsl -> 127.0.0.1 (On)"

This happens with sudo and without. 

Any logs I should provide or is this issue already known and I can move on?

**Comment by cerebrate** [comment]
First off, can I check how you installed genie - was it the prebuilt packages for Arch, or manually?

If the former, can I ask you to try a manual install using genie.tar.gz - those packages are now, I believe, a little way behind the current version.

Otherwise, we can run through some manual debugging steps.

**Comment by dimotsai** [comment]
I had the same problem.

It seems that the systemd process could not be created properly while initializing. It would stick in here: https://github.com/arkane-systems/genie/blob/master/genie/Program.cs#L200-L204

Genie Version:
```
$ genie --version
1.17
```

I was trying to reproduce it by typing the command as below. 
```
$ sudo /usr/bin/unshare -fp --propagation shared --mount-proc /lib/systemd/systemd
unshare: cannot change root filesystem propagation: Invalid argument
```
Don't even know what I was doing though. lol

Any other information I can provide?

**Comment by cerebrate** [comment]
@dimotsai Presumably not exactly the same problem, as 1.17 (which added the --propagation flag) only shipped yesterday.

Which distro and version are you using? Also, which version of util-linux (`unshare -V`)?

**Comment by dimotsai** [comment]
```
$ uname -srm
Linux 4.4.0-17134-Microsoft x86_64

$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

```
$ unshare -V
unshare from util-linux 2.34
```

```
$ cat /proc/self/mountinfo
2 2 0:2 / / rw,noatime - lxfs rootfs rw
3 2 0:3 / /sys rw,nosuid,nodev,noexec,noatime - sysfs sysfs rw
4 2 0:4 / /proc rw,nosuid,nodev,noexec,noatime - proc proc rw
5 2 0:5 / /dev rw,noatime - tmpfs none rw,mode=755
6 5 0:6 / /dev/pts rw,nosuid,noexec,noatime - devpts devpts rw,gid=5,mode=620
7 2 0:7 / /run rw,nosuid,noexec,noatime - tmpfs none rw,mode=755
8 7 0:8 / /run/lock rw,nosuid,nodev,noexec,noatime - tmpfs none rw
9 7 0:9 / /run/shm rw,nosuid,nodev,noatime - tmpfs none rw
10 7 0:10 / /run/user rw,nosuid,nodev,noexec,noatime - tmpfs none rw,mode=755
11 4 0:11 / /proc/sys/fs/binfmt_misc rw,noatime - binfmt_misc binfmt_misc rw
12 2 0:12 / /mnt/c rw,noatime - drvfs C: rw,uid=1000,gid=1000,case=off
13 2 0:13 / /mnt/g rw,noatime - drvfs G: rw,uid=1000,gid=1000,case=off
14 2 0:14 / /mnt/j rw,noatime - drvfs J: rw,uid=1000,gid=1000,case=off
15 2 0:7 /hostname-wsl /etc/hostname rw,nosuid,noexec,noatime - tmpfs none rw,mode=755
16 15 0:7 /hostname-wsl /etc/hostname rw,nosuid,noexec,noatime - tmpfs none rw,mode=755
17 16 0:7 /hostname-wsl /etc/hostname rw,nosuid,noexec,noatime - tmpfs none rw,mode=755
18 17 0:7 /hostname-wsl /etc/hostname rw,nosuid,noexec,noatime - tmpfs none rw,mode=755
19 18 0:7 /hostname-wsl /etc/hostname rw,nosuid,noexec,noatime - tmpfs none rw,mode=755
20 19 0:7 /hostname-wsl /etc/hostname rw,nosuid,noexec,noatime - tmpfs none rw,mode=755
21 20 0:7 /hostname-wsl /etc/hostname rw,nosuid,noexec,noatime - tmpfs none rw,mode=755

**Comment by arlllk** [comment]
Well I maintain the AUR packages, but with dotnet in arch there is the problem that doesn't exist any easy way to use the latest dotnet 3.0 (the last available is 2.2.6+108-1), and from the [AUR submission guidelines](https://wiki.archlinux.org/index.php/AUR_submission_guidelines#Submitting_packages), I can't just make a PKGBUILD from dotnet 3.0 and upload it to the AUR.

I think from what i have seen from other issues is that in the latest versions are a few problems with using an outdated version of dotnet.

Is a very hard situation, the more updated version that is possible to use is the 3.0-RC (3.0.0+100+rc1.014190-1), but i don't know if this don't generate problems with genie, if @cerebrate says that is possible i will update both packages I maintain to use it, that's the best workaround i can think, if anyone has another idea I would be glad to hear them

**Comment by arlllk** [comment]
BTW I don't have any problem using genie, and im using dotnet 2.2.7+402-1, I make that PKGBUILD, you can try it, but this would be a very very horrible workaround

**Comment by cerebrate** [comment]
@arlllk Ah, I didn't realize you were keeping those up to date! Thanks!

I moved 1.17 up to .NET 3.0, but 1.16 and previous are still on 2.2; honestly, for the moment, if there's a convenient way to do it, I might hold the package at 1.16, or at least keep that version available.

There aren't any essential fixes in 1.17; just some cosmetic improvements, and an update to make cross-distro mounting in general and for Docker Desktop's new WSL 2 engine in specific work better with the genie bottle. Since that update's involved in what's causing @dimotsai 's problem, it might be best to hold off on it for now.

**Comment by arlllk** [comment]
I can totally confirm that the problem is with the outdated dotnet version, but one can fix that, I can share the PKGBUILD files for make dotnet 3.0 in Arch, in a tar file
[dotnet-PKGBUILD.tar.gz](https://github.com/arkane-systems/genie/files/3827049/dotnet-PKGBUILD.tar.gz)

**Comment by dimotsai** [comment]
I have followed the README to install dotnet 3.0 manually on my system since genie keep reporting that my dotnet is outdated. I am not sure if this is the same issue.
```
$ dotnet --version
3.0.100
```

I would try @arlllk's PKGBUILD to see if my dotnet was installed incorrectly. Thanks!

**Comment by dimotsai** [comment]
I have installed @arlllk's PKGBUILD but sadly the problem still present. 😢In fact, I haven't succeed to launch systemd yet on both 1.16 and 1.17.

**Comment by dimotsai** [comment]
Just noticed that my WSL was not version 2. I am so Sorry. I didn't know that I have to turn on Windows Insider Program to get WSL 2.

[This doc](https://docs.microsoft.com/en-US/windows/wsl/wsl2-install) says:
> WSL 2 is only available in Windows 10 builds 18917 or higher 

```
C:\Users\Dimo>ver
Microsoft Windows [Version 10.0.17134.1069]
```

I would update the status here after I upgrade to WSL 2.

@Erfboom You might want to check your Windows build version?

**Comment by Erfboom** [comment]
@dimotsai 

`Microsoft Windows [Version 10.0.17763.832]`

So I guess I have WSL 1 and that's where the issue is stemming from?

My dotnet version:

`Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.6 [/opt/dotnet/shared/Microsoft.NETCore.App]`

@cerebrate 

I installed `genie-systemd-git 1.16.r6.gcd8c0bc-1` via AUR.

**Comment by arlllk** [comment]
Okey, the problem is because you are using wsl 1
but from what you installed did you deleted the dependencies after build, the option that spear in yay, because dotnet ask should have been installed

**Comment by Erfboom** [comment]
Yes, I think I did delete the dependencies after install.

I went and installed dotnet 3.0 and it downloaded and extracted the sdk and I made sure not to delete the dependencies but it shows it's not installed. In any case, I have to get wsl 2. 

I'm going to mark this as closed then as the issue was genie has to be ran with wsl 2.

**Comment by dimotsai** [comment]
These are my installed packages and it works very well with WSL 2.
@arlllk @cerebrate Thank you for your works!

```
$ yay -Qi genie-systemd
Name            : genie-systemd
Version         : 1.17-2
Description     : A quick way into a systemd "bottle" for WSL
Architecture    : x86_64
URL             : https://github.com/arkane-systems/genie
Licenses        : custom:The Unlicense
Groups          : None
Provides        : genie-systemd
Depends On      : daemonize  dotnet-runtime  dotnet-host  hostess
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : genie-systemd
Replaces        : None
Installed Size  : 374.01 KiB
Packager        : Unknown Packager
Build Date      : Sun 10 Nov 2019 01:08:24 AM CST
Install Date    : Sun 10 Nov 2019 01:08:30 AM CST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None

$ yay -Qi dotnet-runtime
Name            : dotnet-runtime
Version         : 3.0.0+100-1
Description     : The .NET Core runtime
Architecture    : x86_64
URL             : https://www.microsoft.com/net/core
Licenses        : MIT
Groups          : None
Provides        : dotnet-runtime=3.0.0
Depends On      : dotnet-host  icu  krb5  libunwind  openssl  zlib  libcurl.so=4-64
Optional Deps   : lttng-ust: CoreCLR tracing [installed]
Required By     : aspnet-runtime  dotnet-sdk  genie-systemd
Optional For    : None
Conflicts With  : dotnet-runtime  dotnet-runtime-rc
Replaces        : None
Installed Size  : 66.20 MiB
Packager        : Unknown Packager
Build Date      : Sat 09 Nov 2019 05:20:16 PM CST
Install Date    : Sat 09 Nov 2019 05:30:42 PM CST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None

$ yay -Qi dotnet-sdk
Name            : dotnet-sdk
Version         : 3.0.0+100-1
Description     : The .NET Core SDK
Architecture    : x86_64
URL             : https://www.microsoft.com/net/core
Licenses        : MIT
Groups          : None
Provides        : dotnet-sdk=3.0.0
Depends On      : dotnet-runtime
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : dotnet-sdk  dotnet-sdk-rc
Replaces        : None
Installed Size  : 221.49 MiB
Packager        : Unknown Packager
Build Date      : Sat 09 Nov 2019 05:20:16 PM CST
Install Date    : Sat 09 Nov 2019 05:30:48 PM CST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

**Comment by cerebrate** [comment]
Glad it's working well for you!

**Comment by arlllk** [comment]
Can you put in the Arch space in the readme that modern versions have to install dotnet 3.0 explicitly, and put a link to the comment for the PKGBUILD, like, if they want they can use it, but also they can make their own, and that they have to check always what a PKGBUILD does, for security reasons and good practice

**Comment by cerebrate** [comment]
@arlllk Done!

On another note, as you can see, I've rewritten the build process for _genie_ to use make, with specific targets to locally install (`make install`), build the debian package (`make debian`), etc. While I don't have time or knowledge, alas, to maintain packaging for every distribution, I'd like to collect the package-build processes in the makefile just to have a record of them for future users and maintainers.

What would you think about adding `make arch` to this, maybe?

**Comment by arlllk** [comment]
@cerebrate I could add to especializate a little more, and would be more comfortable because now for every new version I have to manually open the make file and compare, update some parts, but the way I can see Arch functions is to always use packages to handle uninstalling that there is no other way to do it, and I can't see how to adapt the current make files, to be easily usable in Arch, AFAIK there isn't a package to install, all of it is build by the PKGBUILD, the only way that could be possible is to include PKGBUILD, and execute it to make .tar.xz that has to be feeded to pacman to install it

**Comment by lackovic** [comment]
I am having the same problem with:

```sh
$ genie --version
1.27
```

I have installed genie with `yay -S snapd genie-systemd` and was working fine until today: `genie -s` started hanging after running a system update with `yay -Syu` and then downgrading `glibc` to the previous version to [solve an issue with Docker](https://github.com/docker/for-win/issues/8183#issuecomment-680783256).

Using WSL2 with [ArchWSL](https://github.com/yuk7/ArchWSL) on Windows 10 `2004`.

Any idea how I can troubleshoot/fix this?

**Comment by lackovic** [comment]
> Downgrading `systemd-sysvcompat` solved the issue

> I [downgraded glibc using the pacman cache](https://wiki.archlinux.org/index.php/Downgrading_packages#Using_the_pacman_cache) in ArchWSL

Looks like the issue has been fixed and this workaround is not necessary anymore.

After today's updates:
```sh
upgraded harfbuzz (2.7.1-1 -> 2.7.2-1)
upgraded libjpeg-turbo (2.0.5-1 -> 2.0.5-2)
upgraded systemd-libs (246.2-2 -> 246.3-1)
upgraded libcap-ng (0.7.10-1 -> 0.7.11-1)
upgraded libxcrypt (4.4.16-3 -> 4.4.17-1)
upgraded libpsl (0.21.0-2 -> 0.21.1-1)
upgraded llvm-libs (10.0.1-1 -> 10.0.1-2)
upgraded systemd (246.2-2 -> 246.3-1)
```

I removed `systemd-sysvcompat` from `IgnorePkg` in `/etc/pacman.conf` and got:

```
upgraded systemd-sysvcompat (246.2-1 -> 246.3-1)
```

`genie -s` is now working as expected in [ArchWSL](https://github.com/yuk7/ArchWSL).

**Comment by lackovic** [comment]
> `genie -s` is now working as expected in [ArchWSL](https://github.com/yuk7/ArchWSL).

`genie -s` is hanging again after latest updates:

```
linux-api-headers (5.7-1 -> 5.8-1)
glibc (2.32-3 -> 2.32-4)
gcc-libs (10.2.0-1 -> 10.2.0-2)
binutils (2.35-1 -> 2.35-2)
gcc (10.2.0-1 -> 10.2.0-2)
``` 

[The workaround of downgrading `systemd-sysvcompat` to version `246.2-1`](https://github.com/arkane-systems/genie/issues/30#issuecomment-680858231) does not work anymore.

Does anyone have any other idea how to fix/troubleshoot this issue?

**Comment by arlllk** [comment]
I currently working with 

```
linux-api-headers 5.8-1
glibc 2.32-4
gcc-libs 10.2.0-2
binutils 2.35-2
gcc 10.2.0-2
```

And systemd 

```
systemd 246.4-1
systemd-libs 246.4-1
systemd-resolvconf 246.4-1
systemd-sysvcompat 246.4-1
```

and don't have any problems right now.

Do you currently have any [workaround](https://github.com/yuk7/ArchWSL/wiki/Known-issues), that is build in to the default Arch WSL?

**Comment by cerebrate** [comment]
@lackovic Okay, not meaning to be too much of a hardass about this, but step one is _open a separate issue_ . Not all hangs are caused by the same thing, and it's a pain to keep track of new issues showing up in the comments of closed past issues. Not to mention that the original opener of said past issues probably doesn't want to hear about it.

That said - and please respond in a new issue - if you run genie with the -v switch, where in the process does it hang? If you run `genie -i -v` instead of `genie -i -s`, does it hang in the same place?
