### ISSUE TITLE
genie 2.5 showing as 2.4

### ISSUE THREAD

**Issue by luciodaou** [arkane-systems/genie#305]
**Windows version (build number):**
19044.2075

**Linux distribution:**
Ubuntu 22.04.1 LTS (Jammy Jellyfish)

**Kernel version:**
5.10.102.1-microsoft-standard-WSL2

**Genie version:**
2.5, check screenshot

**Describe the bug**
After installing genie 2.5, `genie --version` shows itself as version 2.4 instead of 2.5.

**Confirm that you are running inside the bottle:**
Check screenshot

**To Reproduce**
1. Install genie 2.5
2. Run `genie --version`
3. See error

**Expected behavior**
Show `genie 2.5`

**Screenshots**
![image](https://user-images.githubusercontent.com/53634214/192794622-9e8126c9-6ab5-46d5-8d14-1e57772278a6.png)

**Additional context**
Not a critical stuff but may generate confusion.

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [X] Yes.

**Comment by cerebrate** [comment]
Oops. Thanks for the note; I'll update the packages shortly.
