### ISSUE TITLE
Windows Update KB5015684 - Blackscreen when log in

### ISSUE THREAD

**Issue by Jan25051** [arkane-systems/genie#310]
**Problem:**
I only get a blackscreen instead of the ubuntu-desktop after typing my login information in the vnc-session.

**My temporary Solution:**
For now its just enough to remove update KB5015684 and restart the computer.

**Question:**
Does someone else have problems using wsl2 with lightdm when this Update is installed?
And how can i solve the issue when the update is installed?

Thanks for your advice!

**Comment by cerebrate** [comment]
You probably want to submit this over in Microsoft/WSL or the Ubuntu bug tracker. This repo is for specifically genie-related issues.
