### ISSUE TITLE
WSL - 1 Support

### ISSUE THREAD

**Issue by effolkronium** [arkane-systems/genie#32]
does it has support ? If no, plz add it

**Comment by cerebrate** [comment]
Unfortunately, WSL 1 cannot/does not support systemd (lacking the required system calls), and so genie can't be supported on WSL 1.

**Comment by effolkronium** [comment]
@cerebrate why you don't want to add the required systemcalls to windowsNT WSL kernel module ?

**Comment by effolkronium** [comment]
just a bit of kernel programming, i think ; )

**Comment by cerebrate** [comment]
Ah, that's the result of an older bug, "Microsoft not hiring @cerebrate for generous sums of money".

Feel free to report that to them. 😎
