### ISSUE TITLE
Can't use explorer nor code in genie shell

### ISSUE THREAD

**Issue by takase1121** [arkane-systems/genie#37]
(Re)installed genie, now service works but I can no longer do `explorer.exe .` and `code .` on my genie shell. Works with `genie -i` and non-genie shells. Only shells initialized with `genie -s` doesn't work

![image](https://user-images.githubusercontent.com/20792268/69903205-9eb55d00-13d1-11ea-84de-7db762554532.png)
(`w` is my alias to `wsl genie -s`)

**Comment by arlllk** [comment]
The PATH doesn't get pass to the environment that genie creates, you can try [this](https://github.com/arkane-systems/genie/issues/22#issuecomment-531542300) to pass some PATH to the genie environment

**Comment by takase1121** [comment]
ok thanks!
