### ISSUE TITLE
How to start systemd units when bottle is initialized?

### ISSUE THREAD

**Issue by enko** [arkane-systems/genie#39]
I want to start some units when the bottle ist started, like docker or openvpn. Is this possible or would I need to create a unit on that the other units are depending on that I start when creating the bottle?

**Comment by arlllk** [comment]
Genie should create a complete systemd environment, so you could enable units as is implemented in your Linux distro

**Comment by enko** [comment]
I would expect this unit be started:

```
~ took 4s
➜ genie -s
Deleted DESKTOP-QF7GSBC
Added DESKTOP-QF7GSBC-wsl -> 127.0.0.1 (On)
Starting ssh-agent...
Identity added: /home/tschumacher/.ssh/id_ed25519 (tschumacher@DESKTOP-QF7GSBC)

~
➜ sudo systemctl status docker.service
● docker.service - docker
     Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: disabled)
     Active: inactive (dead)
```

As you can see the unit is enabled, I'm unsure on how to debug this. I'm using archlinux, if you have any tipps on how to proceed I would appreciate this.

**Comment by arlllk** [comment]
In this case to enable systemd in arch you can use
`sudo systemctl enable docker.service`
and to start it you can use 
`sudo systemctl start docker.service`
once enabled it will start automatically at the time of systemd initialization

For more information you can use the [Arch wiki](https://wiki.archlinux.org/index.php/Systemd)

**Comment by cerebrate** [comment]
@enko This isn't a genie problem, specifically; genie starts systemd as a pid 1 instance with no parameters and doesn't intervene afterwards, so everything that happens after that is a standard systemd startup of the default target (as displayed by `systemctl get-default`, probably `multiuser.target`).

That being said, loaded/enabled with the status inactive (dead) _usually_ means that the executable for the unit in question has exited, which suggests that there's probably something broken with your docker install. 

Is that the only output you get from `systemctl status docker` ? Normally, you should get the last journal entries for the service below the status info.

**Comment by enko** [comment]
It seemed my service file was bogus, I used the one provided by my distribution and it worked without a hitch, sorry to waste your time.
