### ISSUE TITLE
Invalid runtimeconfig.json [/usr/local/bin/genie.runtimeconfig.json] [/usr/local/bin/genie.runtimeconfig.dev.json]

### ISSUE THREAD

**Issue by m-j-r** [arkane-systems/genie#4]
Followed the instructions, and now getting the error message:

Invalid runtimeconfig.json [/usr/local/bin/genie.runtimeconfig.json] [/usr/local/bin/genie.runtimeconfig.dev.json]

```
$ sudo cat /usr/local/bin/genie.runtimeconfig.json
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.2",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.2.0"
    },
    "configProperties": {
      "System.Globalization.Invariant": true
    }
  }
}
```

Any help would be appreciated - thanks.
MJR

**Comment by cerebrate** [comment]
Well, that certainly looks correct.

So I can try and repro the issue, could you send me the output of the `dotnet --info` and `lsb_release -a` commands, please?

**Comment by m-j-r** [comment]
Happy to help where I can - I really appreciate you putting this together :-)

```
$ dotnet --info

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.3 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
and
```
$ lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

I know you've only gotten it working on Ubuntu so far, but I can't see why the distro would cause the issue I'm seeing - let me know though.

**Comment by m-j-r** [comment]
Ok, I worked it out - it is a permissions issue.

When I chown-ed to root, I also changed the group - meaning _I_ couldn't access the files... I added read permissions to all of the files for 'all' users ( ```#chmod a+r *```) and now seems to be working fine - thanks so much!
