### ISSUE TITLE
For anyone who struggled with starting genie at boot in Arch complained about libhostfxr.so not found

### ISSUE THREAD

**Issue by Felix-Indoing** [arkane-systems/genie#40]
I managed to work around this problem:

1. `yay -S dotnet-host-bin dotnet-runtime-bin dotnet-sdk-bin genie-systemd-git`
2. create `/etc/dotnet/install_location` and put `/opt/dotnet` inside
3. change WSL startup command to `wsl.exe ~ -d Arch genie -s`

**Comment by cerebrate** [comment]
Thanks. Added to the wiki.

**Comment by tudurom** [comment]
This is no longer necessary and should be removed from the wiki.

**Comment by esgie** [comment]
Confirmed! problem is gone, workaround is no longer needed.
