### ISSUE TITLE
Failed to read server status: Connection reset by peer

### ISSUE THREAD

**Issue by dnstzzx** [arkane-systems/genie#42]
Distro: Arch
Windows Version: 2004

description:
after executing genie -i
# Systemctl status
->Failed to read server status: Connection reset by peer

**Comment by cerebrate** [comment]
Going to need a bit more than that, I'm afraid. Can you send a complete console transcript from before starting WSL through to receiving that error message?

**Comment by dnstzzx** [comment]
How can i get that?
when i executed "genie -i"  in wsl
it printed:
```
Deleted DESKTOP-NJMJBB3
Added DESKTOP-NJMJBB3-wsl -> 127.0.0.1 (On)
```
and when i excuted  " systemctl status"
it only printed:
```
Failed to read server status: Connection reset by peer
```

That's all i'v got

**Comment by cerebrate** [comment]
_genie -i_ just starts the bottle and then exits. To be inside the bottle afterwards requires _genie -s_ or _genie -c_ command; without that, you'll still be outside the bottle. Try it again with the -s option?
