### ISSUE TITLE
invalid command genie: initializing bottle failed; "The old hostname returned 1.

### ISSUE THREAD

**Issue by SDGLBL** [arkane-systems/genie#43]
When I used the command "genie-i", the terminal displayed "invalid command genie: initializing bottle failed; "The old hostname returned 1."
And then I ran "genie - I --verbose true" the terminal displays as follows
```
$ sudo genie -i --verbose true 
genie: no bottle present.
genie: initializing bottle.
genie: dumping WSL environment variables.
genie: generating new hostname.
genie: removing old hostname.
invalid command
genie: initializing bottle failed; removing old hostname returned 1.
```
By looking at the source code I found that the error occurred at [here](https://github.com/arkane-systems/genie/blob/b42a15e60da1e34a62ca27b589163c9dc8aaf276/genie/Program.cs#L253)
But I've installed hostess correctly, and the add command works fine
```
$ sudo hostess add 'hostname'-wsl 127.0.0.1
Added hostname-wsl -> 127.0.0.1 (On)
```
**How to solve this problem**

**Comment by g2proko** [comment]
Same problem with me. The reason is `hostess` command's sub command `del` was changed to `rm` at hostess versions v5.0.2.

## My solutions:
Download the `genie` source code and modify **genie/Program.cs** as follow:

```
$ diff -ruw genie/Program.cs.old genie/Program.cs
--- genie/Program.cs.old	2020-03-15 15:50:59.306739848 +0800
+++ genie/Program.cs	2020-03-15 15:51:16.606025444 +0800
@@ -239,7 +239,7 @@
             if (verbose)
                 Console.WriteLine ("genie: removing old hostname.");
 
-            Chain ("/bin/sh", String.Concat ("-c \"", GetPrefixedPath ("bin/hostess"), " del `hostname`\""),
+            Chain ("/bin/sh", String.Concat ("-c \"", GetPrefixedPath ("hostess"), " rm `hostname`\""),
                        "initializing bottle failed; removing old hostname");
 
             // Set the new hostname.
```
Then, recompile `genie` with `README.md` document.

**Comment by SDGLBL** [comment]
I solved the problem in your way, thank you.

**Comment by cerebrate** [comment]
Working on fixing this to not require hostess; next version should eliminate that dependency.

**Comment by cerebrate** [comment]
A fix eliminating the hostess dependency is in 1.23.
