### ISSUE TITLE
genie: initializing bottle failed; removing old hostname returned 1.

### ISSUE THREAD

**Issue by denglt** [arkane-systems/genie#44]
Centos 8 on wls2
C:\Users\Yuntai1>wsl -l -v
  NAME       STATE           VERSION
* CentOS8    Running         2

when I run genie
[root@desktop-denglt ~]# sudo genie -i -v
genie: no bottle present.
genie: initializing bottle.
genie: dumping WSL environment variables.
genie: generating new hostname.
genie: removing old hostname.
invalid command
genie: initializing bottle failed; removing old hostname returned 1.

**Comment by cerebrate** [comment]
Yeah, there's been a breaking change to hostess; working on it. In the meantime, if you can, reverting to an older version of hostess will function as a workaround.

**Comment by izzues** [comment]
Sorry for the dumb question, but how exactly do I revert to an older version of hostess?

Thanks for the great work :)

**Comment by cerebrate** [comment]
Fixed in 1.23 (out today) by eliminating the dependency on hostess, so if you upgrade to 1.23, that should work.
