### ISSUE TITLE
Can this be published as native executable?

### ISSUE THREAD

**Issue by AlseinX** [arkane-systems/genie#45]
Publish it with [corert](https://github.com/dotnet/corert) then the dependency on a .NET Core 3.0 Runtime could be removed.

**Comment by MaiReo** [comment]
Or we can wait for .NET 5 and publish it as a single file

**Comment by cerebrate** [comment]
I have tested current options for shipping genie as a single executable; the problem with that so far has been that all such options produce a very bloated executable, multiple megabytes in size. Until an option is available that does not produce this effect (and the associated waste of disk space when multiple such are installed on the same system), I'll be keeping the runtime dependency as the least worst option.

**Comment by AlseinX** [comment]
> I have tested current options for shipping genie as a single executable; the problem with that so far has been that all such options produce a very bloated executable, multiple megabytes in size. Until an option is available that does not produce this effect (and the associated waste of disk space when multiple such are installed on the same system), I'll be keeping the runtime dependency as the least worst option.

This is not related to `Single Executable` but `Native Executable`, which is:
+ Statically linked
+ No dependency
+ Faster than JIT compilation

**Comment by cerebrate** [comment]
A statically linked native executable is implicitly a single executable, and indeed, on checking, a native executable compiled with _corert_ comes in at _14 MB_ in size as opposed to 101KB. This is not, by any possible definition of the words, "extremely lightweight". Yes, the 101 KB version requires the (shared) .NET dependency, but preventing every tiny utility from lugging around its own 13.9 MB of overhead is exactly what dynamic linking was intended for.

Unless and until there's a supported first-party option that can produce a native executable without all the bloat, it ain't happening from me. Sorry.
