### ISSUE TITLE
can there be a option for no output?

### ISSUE THREAD

**Issue by esverde** [arkane-systems/genie#46]
what I mean is that I add one line "commandline": "wsl.exe genie -s" to my windows terminal's profile, and it did work while I boot my wsl, but there is always an output on the top of shell.
"Deleted newton
Added newton-wsl -> 127.0.0.1 (On)"
May there be an option like "-q" for no output?
thank lots for your development.

**Comment by cerebrate** [comment]
Fixed in 1.23 (out today) by eliminating the dependency on hostess (the producer of that particular output), so if you upgrade to 1.23, that should work.
