### ISSUE TITLE
[BUG] Failed to install any service using systemctl

### ISSUE THREAD

**Issue by Gsyltc** [arkane-systems/genie#48]
Hi,

I try to install Genie on my WSL2 Debian buster (Official)
But after the install, It's impossible to install another service using systemd

The exemple show the docker installation but it's not the only case (Try with open-jdk, etc....)
___________________________
From a clean install on official Debian WSL

Lib installed : curl wget git golang python make gcc g++ apt-utils lsb-release

**1°) .NET Dependencies installation**

https://dotnet.microsoft.com/download/linux-package-manager/debian9/runtime-3.0.0

a)
```
  $ wget https://packages.microsoft.com/config/ubuntu/19.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  $ sudo dpkg -i packages-microsoft-prod.deb
```

**Passed**

b)
```
  $ sudo apt-get update
  $ sudo apt-get install apt-transport-https
  $ sudo apt-get update
  $ sudo apt-get install dotnet-runtime-3.1
```

**Passed**

**2°) Hostess**

```
  $ git clone https://github.com/cbednarski/hostess
  $ cd hostess
  $ make install
```

```
go build -o bin/hostess .
sudo mv bin/hostess /usr/local/bin/hostess
```

**Passed**  

**3°) Genie Installation**

Amd64 - Buster

```
  $ curl -s https://packagecloud.io/install/repositories/arkane-systems/wsl-translinux/script.deb.sh | sudo bash
  The repository is setup! You can now install packages.

  $ sudo apt install systemd-genie
  $ genie --version
  1.20

  $ genie -i 
  Deleted My-Rog
  Added My-Rog-wsl -> 127.0.0.1 (On)
```

Close terminal et restart
```
  user@My-Rog-wsl:~$ systemctl
  
  UNIT                                                                  LOAD   ACTIVE SUB       DESCRIPTION
  proc-sys-fs-binfmt_misc.automount                                     loaded active running   Arbitrary Executable File
```

**Passed**

**4°) Docker Installation**

```
$ sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

$ curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
ok

$ sudo apt-key fingerprint 0EBFCD88
$ sudo apt update -y
$ sudo apt-get install docker-ce docker-ce-cli containerd.io

**Warning! D-Bus connection terminated.**
**Failed to restart systemd-modules-load.service: Connection reset by peer
See system logs and 'systemctl status systemd-modules-load.service' for details.
Failed to reload daemon: Connection reset by peer
Failed to retrieve unit state: Connection reset by peer
Warning! D-Bus connection terminated.
Failed to start docker.service: Connection reset by peer
See system logs and 'systemctl status docker.service' for details.**
```

_______________________

If services are installed before, It seems to be ok. But I cannot install app or service after.

Do you have an idea ?

Thanks

**Comment by Gsyltc** [comment]
Exemple with openjdk 11


```
Updating certificates in /etc/ssl/certs...
dpkg: error processing package libsm6:amd64 (--configure):
 dependency problems - leaving unconfigured
**dpkg: dependency problems prevent configuration of libxmu6:amd64:
 libxmu6:amd64 depends on libxt6; however:
  Package libxt6:amd64 is not configured yet.**
dpkg: error processing package libatk-wrapper-java-jni:amd64 (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 x11-common
```

Same installation without Genie work well

**Comment by arlllk** [comment]
Hi, to work with genie you need to enter to the environment created `genie -s`, or you can execute the command only in that environment `genie -c <command>`, it's a limitation on the design of WSL 2 and systemd

And this step is not necessary
> Close terminal et restart

**Comment by Gsyltc** [comment]
Ok,

It's a misunderstanding on my side. I figured I could get systemd at startup to run an service like docker or something.

**Comment by arlllk** [comment]
if you add to .bashrc or similar the command `genie -i`, the systemd will open when you run your WSL, but when you open any new terminal will try to run the command, in that case you can put some conditional to check if `/run/genie.env` exist, if that file exist genie is already running

**Comment by Gsyltc** [comment]
Oki, will try this.

Thanks

**Comment by cerebrate** [comment]
@Gsyltc :

@arllk nailed the problem, but you don't want to put `genie -i` in your .bashrc; that initializes the bottle and then exits, but doesn't leave you in the bottle for that shell. (`genie -i` is designed for use in, for example, a .cmd file you run on login with Windows task scheduler or the Startup group to start systemd in a WSL session and then exit (using `wsl genie -i`) if you want to have systemd services started on Windows login and running in the background.

To put yourself into the genie bottle whenever you open a shell, see the solution on the Wiki here:

https://github.com/arkane-systems/genie/wiki/Automatically-start-genie-on-every-shell-session

That's written for zsh, as that's what I use, but it shouldn't be too hard to convert it for bash.
