### ISSUE TITLE
Failed to resolve full path of the current executable [/proc/self/exe]

### ISSUE THREAD

**Issue by GittyMac** [arkane-systems/genie#5]
This is on ArchWSL running dotnet 2.2.105.

**Comment by cerebrate** [comment]
@cerebrate Looks like a CoreCLR error - possibly related to https://github.com/dotnet/coreclr/issues/9014 ?

@GittyMac If you run `la -la /proc/self/exe` from a WSL prompt, what do you get?

**Comment by GittyMac** [comment]
I get `lrwxrwxrwx 1 lako lako 0 Jun 22 11:47 /proc/self/exe -> /usr/bin/ls`

**Comment by GittyMac** [comment]
I didn't correctly setuid /usr/local/bin/genie.
