### ISSUE TITLE
Hangs on `Updated MYPC-wsl -> 127.0.0.1 (On)`

### ISSUE THREAD

**Issue by izzues** [arkane-systems/genie#50]
Whatever option I choose, it hangs. Running `sudo genie -s -v`, this is what I see:
```
genie: no bottle present.
genie: initializing bottle.
genie: dumping WSL environment variables.
genie: generating new hostname.
genie: removing old hostname.
MYPC not found in /etc/hosts
genie: setting new hostname.
Updated MYPC-wsl -> 127.0.0.1 (On)
genie: starting systemd.
```
So I have to press `Ctrl+C` to leave.

Notes:
* I'm using genie with [Arch Linux](https://aur.archlinux.org/packages/genie-systemd/).
* I added the [script to auto enter the bottle](https://github.com/arkane-systems/genie/wiki/Automatically-start-genie-on-every-shell-session), but this happens even if I cancel it.
* I'm using zsh, but it also happens in bash.

**Comment by cerebrate** [comment]
Yeah, hostess made a breaking change eliminating a command genie depended on. Fixed in 1.23 (out today) by eliminating the dependency on hostess, so if you upgrade to 1.23, that should work.

**Comment by izzues** [comment]
Awesome! I see the update is already in the Releases page, but not on AUR. Will it be posted there or should I install from here?

**Comment by cerebrate** [comment]
I'm not the maintainer of the AURs, but it should hopefully work its way through. In the meantime, if you replace the files in /usr/bin with the new ones from the release, that should be all you need.

**Comment by arlllk** [comment]
Hi, mainteiner of the AUR package, I currently don't have internet, and don't have an ETA for when I'm gonna have it back, the necessary changes should be kinda easy tweaking some things on the PKGBUILD, sorry :/

**Comment by izzues** [comment]
Hey @arlllk! No problem, thanks for the info.

I don't know how contributing to AUR works. Is there any way to let someone else update it? Like add someone as a contributor or something like that?

**Comment by arlllk** [comment]
I know that is possible, but don't know how, flag it as outdated, if they aren't please

**Comment by izzues** [comment]
Oh, found it:

https://wiki.archlinux.org/index.php/User:Quequotion/AUR_submission_guidelines#Maintaining_packages

> Additional maintainers can be added to or removed from a package by clicking "Manage Co-Maintainers" under "Package Actions" on the right of its AUR page and editing the list.

When you say you "don't have internet", do you mean you don't even have access to the AUR? Or would you be able (and willing) to add a co-maintainer? Would @cerebrate like to become one? (I'd gladly do so, but I'd understand if you don't consider me to be trustworthy.)

**Comment by cerebrate** [comment]
Unfortunately, I don't have an Arch install handy or the time to properly fill the maintainer role myself, so I must sadly decline.

**Comment by arlllk** [comment]
Hello, I finally could update and added the user that make an updated and posted in the comments in AUR as a co-manteiner, sorry for the problems.  And thanks to the one who posted that update

**Comment by cerebrate** [comment]
Thanks muchly!
