### ISSUE TITLE
systemctl --user: Failed to connect to bus: No such file or directory

### ISSUE THREAD

**Issue by christopher-dG** [arkane-systems/genie#51]
I'm using genie with Arch Linux in WSL2 (`genie-systemd` AUR package). It's been working great for some time, but in the last few days, I've noticed that running `systemctl` in user mode (`--user`) often does not work. I always get the error:

```
Failed to connect to bus: No such file or directory
```

As root, everything works fine. I can `sudo systemctl start docker`, etc. The usermode problem persists until I kill WSL (by running `wsl --shutdown` or `poweroff` from WSL), then in a new WSL session, it tends to work fine.

Is there any log file that I can inspect to debug genie's initialization?

Lastly, thanks for this package, it's immensely useful to me. ❤️ 

Edit: A bit more info on my setup: My WSL sessions are always in genie, as my terminal command is `wsl.exe genie -c tmux`.

**Comment by cerebrate** [comment]
There's not a log file, unfortunately, but you can get a read on genie's initialization by using the _-v_ option.

That being said, I'm not sure if this is a genie issue, since once the bottle is established with its pid 1 systemd, running the user systemd should just be between the systemd instances and dbus. That error looks like the systemd user-session daemon plain isn't running. Does `systemctl status` and/or `ps x` show it?

How are you starting it? I start mine with _pam_systemd_, which I have configured in the `/etc/pam.d/runuser-l` file to start along with my login shell, but if you're using `genie -c` rather than _genie -s_, that's not starting a login shell.

**Comment by cerebrate** [comment]
Also, does the DBUS_SESSION_BUS_ADDRESS environment variable exist both when it works and when it doesn't?

I note that on my system, it is present in my usual way of starting WSL (genie -s), which creates a login shell. However, `genie -c zsh` does _not_ create a login shell, and the variable is missing, unless forced with `genie -c zsh -l` .

**Comment by christopher-dG** [comment]
You're right -- when it's not working, `systemd --user` is simply not running.
I ran `wsl` from PowerShell to help debug:

```
PS C:\Users\Chris> wsl --shutdown
PS C:\Users\Chris> wsl
shoebox [ /mnt/c/Users/Chris ] genie -v -s
genie: no bottle present.
genie: initializing bottle.
genie: dumping WSL environment variables.
genie: generating new hostname.
genie: removing old hostname.
Deleted shoebox
genie: setting new hostname.
Added shoebox-wsl -> 127.0.0.1 (On)
genie: starting systemd.
genie: starting shell
envar: INSIDE_GENIE=true
envar: WSL_DISTRO_NAME=Arch
envar: WSL_INTEROP=/run/WSL/7_interop
envar: WSLENV=WT_SESSION::WT_PROFILE_ID
shoebox-wsl [ ~ ] ps aux | grep systemctl
degraafc     105  0.0  0.0   6288  2300 pts/0    S+   15:06   0:00 grep systemctl
shoebox-wsl [ ~ ] ps aux | grep systemd
root           1  0.6  0.0  25664 11140 ?        Ss   15:06   0:00 /lib/systemd/systemd
root          23  2.2  0.0  37708 11844 ?        Ss   15:06   0:00 /usr/lib/systemd/systemd-journald
root          30  2.4  0.0  31456  8868 ?        Ss   15:06   0:00 /usr/lib/systemd/systemd-udevd
dbus          87  0.0  0.0   6644  3520 ?        Ss   15:06   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root          88  1.5  0.0  17300  6932 ?        Ss   15:06   0:00 /usr/lib/systemd/systemd-logind
degraafc     120  0.0  0.0   6288  2264 pts/0    S+   15:06   0:00 grep systemd
shoebox-wsl [ ~ ] systemctl --user status emacs
Failed to connect to bus: No such file or directory
```

Could you explain your pam_systemd setup a bit more? I've never used that before, so maybe it would fix my issues.

**Comment by christopher-dG** [comment]
When it doesn't work, no `DBUS_SESSION_BUS_ADDRESS`. When it does, `DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus`.

**Comment by cerebrate** [comment]
Disclaimer: I'm a Debian user, so there may be differences on Arch, although [per ArchWiki](https://wiki.archlinux.org/index.php/PAM) at least, Arch does implement PAM.

So, to log on to the bottle under the correct user, genie invokes [runuser(1)](https://linux.die.net/man/1/runuser). If genie -s, it uses runuser -l (which makes it a login shell, simulating as best I can an actual Linux login); if genie -c , it doesn't, it just runs the command wrapped in a script that fixes up the environment.

When anything logs on a user - login, su, runuser, anything - it calls a bunch of PAM modules specified in the matching file under /etc/pam.d to do various authentication-related things. (In the case of runuser, those files are runuser for non-login shells, and runuser-l for login shells. So in my /etc/pam.d/runuser-l, I have this:

```
#%PAM-1.0
auth            include         runuser
session         optional        pam_keyinit.so force revoke
-session        optional        pam_systemd.so
session         include         runuser
```

The important line there is the `-session optional [pam_systemd.so](https://manpages.debian.org/stretch/libpam-systemd/pam_systemd.8.en.html)` one, which informs systemd-logind that someone has just logged in, and that then sets up the user session and all the associated stuff like the systemd user instance automatically.
