### ISSUE TITLE
'/lib/genie/dumpwslenv.sh ': No such file or directory

### ISSUE THREAD

**Issue by izzues** [arkane-systems/genie#52]
I'm on Arch WSL, zsh.

```zsh
izzues% git clone https://github.com/arkane-systems/genie/
izzues% cd genie
izzues% make install
izzues% /usr/local/bin/genie -s  # Happens with or without sudo
genie: error executing command '/lib/genie/dumpwslenv.sh ':
No such file or directory
```

**Comment by cerebrate** [comment]
Oops, look like some commits went missing there. I'll fix that.

**Comment by cerebrate** [comment]
Fixed now; it only seriously affects the local installs, so no new release, but pull the update to your local repo and make install again, and it should work.

**Comment by izzues** [comment]
Thanks! Now it just hangs though:

```
$ genie -s -v
genie: no bottle present.
genie: initializing bottle.
genie: dumping WSL environment variables.
genie: generating new hostname.
genie: external hostname is MYPC
genie: updating hosts file.
genie: setting new hostname.
genie: starting systemd.
```

**Comment by izzues** [comment]
Possibly related to the hanging: I haven't turned off the computer since I last commented. I've just opened Task Manager and noticed (by accident) that there are 4 `genie` processes running, and each consuming around the same amount of memory (11.5 MB), although there are no WSL windows open.

**Comment by cerebrate** [comment]
Waitwaitwait... in Task Manager? Something is _all kinds_ of weird here, because WSL 2 processes (unlike WSL 1 processes) don't show up in Task Manager; they run inside a light vm, so all you should see is a vmmem process containing all your WSL sessions.

Send screenshot, plz? (Also, if possible, output of _wsl -l -v_ and your Windows build number.)

**Comment by izzues** [comment]
Oh... That answers so many things...

You're absolutely right. *All* my distros are on WSL 1, even the ones I installed after upgrading Windows to 2004 Insider. I don't know how I have missed that for so long.

I'll be upgrading them and if everything goes right I'll be leaving you alone. THANK YOU so much in advance and sorry for bothering!

**Comment by cerebrate** [comment]
No worries, glad we got that sorted out.

If you could, please send the _mount_ output for the WSL distro you were trying genie on before you upgrade that one to WSL 2. There's a related test in genie that's supposed to detect WSL 1 and display an appropriate error message, and I'd like to figure out why that's not working.

Thanks!

**Comment by izzues** [comment]
Here it is:

```
rootfs on / type wslfs (rw,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
C:\ on /mnt/c type drvfs (rw,noatime,uid=1000,gid=985,case=off)
G:\ on /mnt/g type drvfs (rw,noatime,uid=1000,gid=985,case=off)
```

(I had already upgraded when I read your comment, but then I downgraded again using `wsl --set version Arch 1` so I could run the command for you. That shouldn't screw with the output you wanted, right?)

**Comment by cerebrate** [comment]
No, that's perfect, thanks!

genie uses the type of the root file system to determine if it's running under WSL 1, and it looks like Microsoft changed that from _lxfs_ to _wslfs_ at some point. So once 1.24 ships in a few days, this shouldn't happen in the future.
