### ISSUE TITLE
Ubuntu 20.04 sopport please

### ISSUE THREAD

**Issue by HuJK** [arkane-systems/genie#55]
Microsoft's apt source no longer provide dotnet-runtime-3.0, it provide dotnet-runtime-3.1 now, So I can't install systemd-genie

Now default installation of Ubuntu is Ubuntu 20.04 in Microsoft Store. Rebuild dependence tree and republish it, please~

**Comment by yzgyyang** [comment]
+1

**Comment by NightmareZero** [comment]
+1

**Comment by nerumo** [comment]
it's not the only thing that needs changing: daemonize changed its install path from `/usr/sbin/daemonize` to `/usr/bin/daemonize`

**Comment by cerebrate** [comment]
Ah, such careful attention to backwards compatibility. Gotta love that.

Thanks for the PR, @nerumo .

**Comment by BenGrn** [comment]
> it's not the only thing that needs changing: daemonize changed its install path from `/usr/sbin/daemonize` to `/usr/bin/daemonize`

You can't apt-get daemonize in 1604 at all. You need to git clone and build which changes its install to 
`/usr/local/sbin/daemonize`

**Comment by seffyroff** [comment]
FWIW I was able to build myself on Focal with no issue.

**Comment by cerebrate** [comment]
Should be fixed in 1.24, available now in the repo for both recent Debians and Focal.
