### ISSUE TITLE
D-bus connection terminated   && failed to talk to init daemon

### ISSUE THREAD

**Issue by elswerky** [arkane-systems/genie#6]
i followed your tutorial on Arch wsl  on wsl2 
but when i try to run a systemd service i get D-bus connection terminated 

also if i run 
$ sudo reboot 
i get : 
falied to talk to init daemon
 
any help ??

**Comment by cerebrate** [comment]
If you run `ps aux`, do you see dbus-daemon running? If so, do you get any output from `busctl`, or a similar error message?

Also, do you get the same error if you start dbus manually prior to running `genie -s` / `genie -c` ?

**Comment by cerebrate** [comment]
Closed as stale.
