### ISSUE TITLE
Can't access MySQL after installing with Genie except sudoing through Genie

### ISSUE THREAD

**Issue by selfagency** [arkane-systems/genie#61]
I installed MySQL server under WSL2 using Genie so that the system services would properly register as background processes in WSL. I did the same for PHP. Both services are now up and running. Yay! But, I can't access MySQL unless I go through Genie as a sudoer. If I try to access MySQL on the command line, it fails unless I preface the command with `sudo genie -c`. If I try to access the database via PHP or via a DB administration GUI, it fails to connect. Here's some command-line output to illustrate the problem.

```bash
wiki on  release [✘] via ⬢ v12.18.0 via 🐘 v7.4.7
❯ mysql -u root -p
Enter password: 
ERROR 1698 (28000): Access denied for user 'root'@'localhost'

wiki on  release [✘] via ⬢ v12.18.0 via 🐘 v7.4.7 took 2s
❯ genie -c mysql -u root -p
Enter password: 
ERROR 1698 (28000): Access denied for user 'root'@'localhost'
genie: running command failed; nsenter returned 1.

wiki on  release [✘] via ⬢ v12.18.0 via 🐘 v7.4.7 took 3s
❯ sudo genie -c mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 429
Server version: 5.7.30-0ubuntu0.18.04.1 (Ubuntu)

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit
Bye
```

**Comment by cerebrate** [comment]
Hm. The second result there is odd; _genie_ is failing when run without _sudo_, which shouldn't be the case. Can you confirm that `/usr/bin/genie` hasn't somehow lost its setuid bit?

(Also, do I take it correctly that you're issuing all these sample commands from outside the bottle?)
