### ISSUE TITLE
Preferred locale is not set when running `genie -s`

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [arkane-systems/genie#62]
## Reproduction
1. Install Ubuntu via Microsoft Store (I use 20.04)
1. Install genie via instructions from README
1. Configure deviation file via <https://github.com/arkane-systems/genie#deviations-file>
1. Run `dpkg-configure locales` as root in the WSL2 Ubuntu session, select a non en_US locale (I use `zh_TW.UTF-8 UTF-8`)
1. In the "select default locale" step, select a non en_US locale(I use `zh_TW.UTF-8`)
1. Exit Ubuntu session
1. Run `wsl --shutdown` in the Windows terminal
1. Run `wsl genie -s` command in the Windows terminal
1. Run `locale` in the bottle'd environment

## Expected Behavior
The following output is printed:

```
LANG=zh_TW.UTF-8
LANGUAGE=
LC_CTYPE="zh_TW.UTF-8"
LC_NUMERIC="zh_TW.UTF-8"
LC_TIME="zh_TW.UTF-8"
LC_COLLATE="zh_TW.UTF-8"
LC_MONETARY="zh_TW.UTF-8"
LC_MESSAGES="zh_TW.UTF-8"
LC_PAPER="zh_TW.UTF-8"
LC_NAME="zh_TW.UTF-8"
LC_ADDRESS="zh_TW.UTF-8"
LC_TELEPHONE="zh_TW.UTF-8"
LC_MEASUREMENT="zh_TW.UTF-8"
LC_IDENTIFICATION="zh_TW.UTF-8"
LC_ALL=
```

## Current behavior
The following output is printed:

```
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

### Windows
10.0.19042.330 (Insiders 20H2)

## Additional information
`wsl genie -c locale` doesn't seem to reproduce this issue

**Comment by cerebrate** [comment]
When you say "`wsl genie -c locale` doesn't seem to reproduce this issue", do you mean that the locale appears to be set correctly when you run that command?

Also, did you run the `dpkg-configure locales` command inside or outside the bottle?

**Comment by Lin-Buo-Ren** [comment]
Apologies for the ignorance.

> When you say "`wsl genie -c locale` doesn't seem to reproduce this issue", do you mean that the locale appears to be set correctly when you run that command?

Yes.

> Also, did you run the `dpkg-configure locales` command inside or outside the bottle?

I run the command inside the bottle.

**Comment by cerebrate** [comment]
I'm afraid that I've been unable to reproduce this problem here. It's also a pretty confusing issue because there really shouldn't be any difference in the locale between the genie -c environment and the genie -s environment, since they're inside the same bottle. Still, there are a couple more things to try -

If you run your default shell via _genie -c_, i.e. `genie -c /usr/bin/bash` (or whichever shell you use), then run locale inside the resulting shell, which result do you get?

Also, can you let me have the contents of your `/etc/pam.d/runuser` and `/etc/pam.d/runuser-l` files?

**Comment by cerebrate** [comment]
Hm. I have finally managed to get a partial repro. If you're still experiencing the problem, could you try adding the line

```
session       required   pam_env.so readenv=1 envfile=/etc/default/locale
```

to `/etc/pam.d/runuser-l`.
