### ISSUE TITLE
FileNotFoundException for Newtonsoft.Json

### ISSUE THREAD

**Issue by farzadmf** [arkane-systems/genie#66]
Hi, I have installed [`genie-systemd`](https://aur.archlinux.org/packages/genie-systemd) from Arch AUR repository.

The package was flagged out of date for a long time, but now it seems to be update to the latest version, but after the update, when I try to start WSL, I get the following error:
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.

File name: 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at ArkaneSystems.WindowsSubsystemForLinux.Genie.Locations..ctor()
   at ArkaneSystems.WindowsSubsystemForLinux.Genie.Program.Main(String[] args)
```

Can you please tell me how I can fix this? It's basically rendered my WSL as unusable 😓

**Comment by arlllk** [comment]
Sorry, my bad, I will fixit

**Comment by farzadmf** [comment]
So, for the time being and until the issue is properly fixed, I managed to eliminate the error by copying `Newtonsoft.Json.dll` to `/usr/bin` and copying `deviated-preverts.conf` to `/usr/lib/genie`

But then just to test something, I ran `wsl --terminate <my-arch-distro>`, and now I see the following message:
```
genie: unable to locate 'systemd'. Please update deviations file.
```

Can you please help me fix this issue?

**Comment by arlllk** [comment]
I just pushed the new revision:
I forgot to include the new library `Newtonsoft.Json.dll`
And from a recent [pull request](https://github.com/arkane-systems/genie/pull/65#issue-452664027) from @wanghaiwei  copied the `deviated-preverts.con`

Sorry for the mistakes and I will be back to be active as maintainer of the package in AUR

**Comment by farzadmf** [comment]
Thank you @arlllk, honestly, I didn't expect such a quick answer 🙂

**Comment by farzadmf** [comment]
Updated the package and everything seems to be working fine, so I'm going to close this.

Again, thank you @arlllk , I really appreciate the quick response and GREAT JOB updating the AUR package. AMAZING JOB 🚀

**Comment by farzadmf** [comment]
@arlllk  this is more a question rather than an issue:

As you know, Arch is not "officially" supported (meaning that it's not in the Windows Store). So I have used [yuk7/ArchWSL](https://github.com/yuk7/ArchWSL) to install it, and, as you probably already know, it's using WSL 2.

Now, my question is that when I start my distribution without `genie -s`, it's like that for every single operation, it's dying to do something; everything is SUUUPER slow, but when I start the distribution with `genie -s`, it seems that heaven doors have opened and I can safely say it runs 10x faster!!!

Does this have any logical reasoning, or it's only coincidence that this is happening?

I have Ubuntu installed too, but I'm not using it (I don't have everything set up there), but in Ubuntu, the speed seems to be fine without `genie` (I haven't even installed `genie` there and I can't run `systemctl` in that distribution)

**Comment by arlllk** [comment]
Y use that Arch version too.

The thing that I can say from my experience and in my computer (maybe is a particular quirk) is that a lot of programs have silent exceptions in arch when not running `systemd` because there are a lot of very important environment variables that aren't set:

- `DBUS_SESSION_BUS_ADDRESS`
- `XDG_CONFIG_HOME`
- `XDG_RUNTIME_DIR`
- `XDG_SESSION_CLASS`
- `XDG_SESSION_ID`
- `XDG_SESSION_TYPE`

In GUI apps when they are executed throws A LOT of errors in the console because those variables are not set.

I guess that these are normally added by compatibility from the distros when they support officially WSL.

**Comment by farzadmf** [comment]
Great answer @arlllk , thank you 😀

**Comment by cerebrate** [comment]
That said, in Debian or Alpine (for example) those variables aren't set either without genie; my default outside-the-bottle environment looks like this:

```
USER=avatar
WT_PROFILE_ID={58ad8b0c-3ef8-5f4d-bc6f-13e4c00f2530}
SHLVL=1
HOME=/home/avatar
WSL_DISTRO_NAME=Debian
LOGNAME=avatar
WSL_INTEROP=/run/WSL/6_interop
NAME=athena
TERM=xterm-256color                                                                                                                                  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:...
WT_SESSION=df4ff10f-a718-415c-954e-0a1c730db544
LANG=en_US.UTF-8
SHELL=/usr/bin/zsh
PWD=/mnt/c/Users/avatar
HOSTTYPE=x86_64                                                                                                                                      WSLENV=WT_SESSION::WT_PROFILE_ID
```

...nor are dbus-daemon, etc., running. Perhaps Arch is more dependent on these services than most distros?
