### ISSUE TITLE
Once stopped, no way to start it up again (RH)

### ISSUE THREAD

**Issue by das-rob3rt** [arkane-systems/genie#73]
(This should be an issue I've created a few days ago, however I was just too busy preparing my job interview to do so.) :-|

```
PS C:\> wsl -d rhwsl8 genie -u
PS C:\> wsl -d rhwsl8 genie -s
Failed to create CoreCLR, HRESULT: 0x80004005
PS C:\>
```

The problem basically looks just like this. Executing `wsl -t rhwsl8` would fix this, however.

Besides, there's one more thing I have noticed.

```
$ dotnet --version
Failed to create CoreCLR, HRESULT: 0x80004005
```

After executed `genie -u`, even `dotnet` command itself may fail.

**Comment by arlllk** [comment]
AFAIK there is not `genie -u`, to initialize is `genie -i`. maybe a typo?

**Comment by cerebrate** [comment]
@arlllk New feature in the latest version. :)

**Comment by arlllk** [comment]
oh, I can't make the last version work, and I don't have to much time to troubleshot, sorry

**Comment by cerebrate** [comment]
Given the changes in the last version (and what I know about Arch-vs-everything), I'd guess that it's almost certainly something funky with the secure path in the new /etc/genie.ini config file. I've added "/lib/systemd" to the start of that path for the next release (1.27, probably being shipped in the next day or so), for strict FHS-compliance per #71, so that might be the problem. If not, checking that all the utilities genie calls are in one of those secure-path folders is probably the next thing on the list.

**Comment by cerebrate** [comment]
@das-rob3rt The underlying issue you're probably running into here is that genie isn't idempotent; the bottle isn't perfect, and so it's possible for systemd within the bottle to change the system's state in ways that aren't reverted on bottle exit (and, of course, the kernel and its settings are shared across all WSL distros inside and outside any bottles anyway).

I'm going to see what can be improved here without adding too much overhead (although I note that that dotnet problem doesn't occur on my Debian distro), but for now at least, my recommendation is always to terminate the distro after running _genie -u_ to ensure you start up with a clean slate.

I've added this to the BUGS section of the README.

**Comment by arlllk** [comment]
I hope that fix it,  I will try to find time to check the next release and if it doesn't get fixed I will try to find the culprit.

**Comment by cerebrate** [comment]
1.27 out now. Note: big changes in layout and debian package-build process (debuild) with this one, which will probably mean rejigging the Arch packager.

**Comment by das-rob3rt** [comment]
> 1.27 out now. Note: big changes in layout and debian package-build process (debuild) with this one, which will probably mean rejigging the Arch packager.

Appreciate your elegant work. This will be followed up in the next RHWSL8 release. ;)
PS: I am currently working at baking an RPM package for this `genie`. I will make a PR some days later.

**Comment by arlllk** [comment]
Both packages in AUR are updated (the new build system is awesome) .

And @das-rob3rt  bug I can't replicate it in Arch.

**Comment by das-rob3rt** [comment]
> Both packages in AUR are updated (the new build system is awesome) .
> 
> And @das-rob3rt bug I can't replicate it in Arch.

When I was issuing this issue, I was using release 1.26 with symlinking `/lib/systemd/systemd` to `/sbin/systemd`.

When shipped with the latest 1.27 release, without any manual symlinking, however, the `Failed to create CoreCLR` issue disappeared.

If you are shipping the 1.27 release on Arch, then you might not replicate this problem. However, if you shipped 1.26 release with manual symlink (afaik Arch respects FHS strictly as well), then you might be able to replicate this issue.

I should have mentioned the exact version when I was issuing this. Apologies.

**Comment by arlllk** [comment]
I had problems with 1.26, that didn't solve, that why I skipped some versions.

I guess the problem was this in RH also
> Given the changes in the last version (and what I know about Arch-vs-everything), I'd guess that it's almost certainly something funky with the secure path in the new /etc/genie.ini config file. I've added "/lib/systemd" to the start of that path for the next release (1.27, probably being shipped in the next day or so), for strict FHS-compliance per #71, so that might be the problem. If not, checking that all the utilities genie calls are in one of those secure-path folders is probably the next thing on the list.

**Comment by cerebrate** [comment]
Looks like this is cleared up for now, so I'm going to go ahead and close.
