### ISSUE TITLE
Dependencies declaration in auto-generated (?) RPM package needs modification

### ISSUE THREAD

**Issue by das-rob3rt** [arkane-systems/genie#74]
This is a dry attempt in an RHUBI 8 container.

```
bash-4.4# dnf localinstall systemd-genie-1.27-1.x86_64.rpm
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Red Hat Universal Base Image 8 (RPMs) - BaseOS                                          120 kB/s | 768 kB     00:06
Red Hat Universal Base Image 8 (RPMs) - AppStream                                       545 kB/s | 3.9 MB     00:07
Red Hat Universal Base Image 8 (RPMs) - CodeReady Builder                               3.2 kB/s |  11 kB     00:03
Last metadata expiration check: 0:00:01 ago on Thu Aug 20 04:18:07 2020.
Error:
 Problem: conflicting requests
  - nothing provides daemonize needed by systemd-genie-1.27-1.x86_64
  - nothing provides policykit-1 needed by systemd-genie-1.27-1.x86_64
  - nothing provides libc6 >= 2.14 needed by systemd-genie-1.27-1.x86_64
  - nothing provides libgcc-s1 >= 3.0 needed by systemd-genie-1.27-1.x86_64
  - nothing provides libstdc++6 >= 4.6 needed by systemd-genie-1.27-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

(Note that when it comes to system utilities, there's no difference between RHUBI 8 repo and RHEL 8 repo.)

The fact is:
1. `daemonize` is not available in RHEL 8 / CentOS 8
2. The `policykit-1` package in RH's world is called `polkit`
3. The `libc6` should be `glibc`
4. `libgcc-s1` is not even available in Debian's repo. And the equivalent in RH should be `libgcc`
5. `libstdc++6` should be `libstdc++`
6. The version of `runuser` in RHEL 8 is somehow lower than other major distros, causing no `-w` option. The current workaround is to "borrow" the `runuser` binary from others, and place it under `/usr/local/sbin`.

PS: Since `daemonize` is not provided in RHEL 8 / CentOS 8, author you might want to consider bundle the binary and manpage within this `systemd-genie` package to deliver them together.

PPS: Afterall, why is `-w` option needed anyway? I've read the source code of `genie` and I still can't get it... Any explanation would be appreciated.

**Comment by cerebrate** [comment]
Re PPS: ordinarily, runuser -l resets the environment block, because it's simulating a login shell. -w tells it to whitelist the envars whose names follow, which lets me pass through the genie-relevant environment variables into the new user session when I otherwise couldn't.

**Comment by cerebrate** [comment]
After poking at this and doing some more testing, I'm gonna declare the auto-transformation into other package types experiment a failure and pull it. Thanks for testing it out.
