### ISSUE TITLE
all unit.service is fail after executing genie -s

### ISSUE THREAD

**Issue by robertzhangwenjie** [arkane-systems/genie#77]
root@IT74-L-6DSBK12-wsl:/home/robert# systemctl status sshd
● ssh.service - OpenBSD Secure Shell server
     Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2020-09-04 10:21:14 CST; 12min ago
       Docs: man:sshd(8)
             man:sshd_config(5)

Sep 04 10:21:14 IT74-L-6DSBK12-wsl systemd[1]: ssh.service: Control process exited, code=exited, status=1/FAILURE
Sep 04 10:21:14 IT74-L-6DSBK12-wsl systemd[1]: ssh.service: Failed with result 'exit-code'.
Sep 04 10:21:14 IT74-L-6DSBK12-wsl systemd[1]: Failed to start OpenBSD Secure Shell server.
Sep 04 10:21:14 IT74-L-6DSBK12-wsl systemd[1]: ssh.service: Scheduled restart job, restart counter is at 5.
Sep 04 10:21:14 IT74-L-6DSBK12-wsl systemd[1]: Stopped OpenBSD Secure Shell server.
Sep 04 10:21:14 IT74-L-6DSBK12-wsl systemd[1]: ssh.service: Start request repeated too quickly.
Sep 04 10:21:14 IT74-L-6DSBK12-wsl systemd[1]: ssh.service: Failed with result 'exit-code'.
Sep 04 10:21:14 IT74-L-6DSBK12-wsl systemd[1]: Failed to start OpenBSD Secure Shell server.
root@IT74-L-6DSBK12-wsl:/home/robert# systemctl status docker
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2020-09-04 10:24:13 CST; 11min ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
   Main PID: 1663 (code=exited, status=1/FAILURE)

Sep 04 10:24:13 IT74-L-6DSBK12-wsl systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Sep 04 10:24:13 IT74-L-6DSBK12-wsl systemd[1]: Stopped Docker Application Container Engine.
Sep 04 10:24:13 IT74-L-6DSBK12-wsl systemd[1]: docker.service: Start request repeated too quickly.
Sep 04 10:24:13 IT74-L-6DSBK12-wsl systemd[1]: docker.service: Failed with result 'exit-code'.
Sep 04 10:24:13 IT74-L-6DSBK12-wsl systemd[1]: Failed to start Docker Application Container Engine.

**Comment by cerebrate** [comment]
Which distribution are you using? Also, can you send the complete output of `systemctl status`, and of `journalctl -xe` immediately after starting the distribution and running `genie -s`?

**Comment by robertzhangwenjie** [comment]
@cerebrate  My system info is below: 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

Version:  windows 10 enterprise
Version Num: 2004
OS version: 19041.450
