### ISSUE TITLE
Failed to retrieve unit state: Connection reset by peer Failed to get properties: Connection reset by peer

### ISSUE THREAD

**Issue by robertzhangwenjie** [arkane-systems/genie#78]
After exiting the bottle, i encounter the fllowing error message, and command 'service' does not work! 

Failed to retrieve unit state: Connection reset by peer
Failed to get properties: Connection reset by peer

**Comment by arlllk** [comment]
When you go out of the bottle, you can't access any service, that's why that message appears, any interaction with any service must be make inside the bottle.

That is a limitation of WSL 2

**Comment by cerebrate** [comment]
As @arlllk said. _service(8)_ depends on _systemctl(1)_, which only functions inside a systemd context, i.e., the genie bottle.

Additionally, it is strongly recommended not to continue to use the WSL 2 session after exiting the genie bottle without terminating and restarting that distribution. systemd services may change various settings in ways that genie has no control over, and thus genie cannot be idempotent; as such, the behavior of WSL 2 after exiting the bottle is undefined.
