### ISSUE TITLE
genie: not executing under WSL 2 - how did we get here?

### ISSUE THREAD

**Issue by Herbert256** [arkane-systems/genie#79]
Running genie gives this error

```
PS C:\Users\herbert> wsl -l -v
  NAME       STATE           VERSION
* php80      Stopped         2
  mariadb    Stopped         2
  php74      Stopped         2
  ubuntu     Running         2
PS C:\Users\herbert> wsl -d ubuntu
root@linux:~# genie -s
genie: not executing under WSL 2 - how did we get here?
root@linux:~#
```

because installling with apt gives currently the error " 429 Too Many Requests"  I have installed genie with below statements

```
cd /tmp
git clone https://github.com/arkane-systems/genie.git
cd genie/genie
make local
```

**Comment by cerebrate** [comment]
Yeah, the 429 error is my repo host running out of quota again. Sigh.

The WSL 2 check looks for the `/run/WSL` directory, created by WSL automatically. Can you confirm whether or not it exists in your distribution? Also, if it doesn't, can you try `mkdir -p /run/WSL` and then running genie?

**Comment by Herbert256** [comment]
No /run/WSL directory, Ubuntu 20.04 ( no idea if relevant, but it was not the default Windows Store installation but created with the wsl --import option )

Because /run is setup at boot time I removed the !IsWsl2 check in Program.cs and then a 'make local' again, also below was needed to get genie running

ln -s /usr/local/libexec/genie /usr/libexec/genie

**Comment by Herbert256** [comment]
I found the reason why there is no /run/WSL directory, it's because of below /etc/wsl.conf I created

[automount]
enabled=false

[interop]
enabled=false

**Comment by dark-swordsman** [comment]
Just to add onto the 429 error, I can no longer do `sudo apt-get update` for other things because of this error. :)

I was trying to [add repos](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software) tp get `dotnet-sdk-3.1` so I can use this on Ubuntu, but I ran into that error.

**Comment by cerebrate** [comment]
Yeah, looks like @evertheylen and I missed this one when examining #75 . I'll add a compromise WSL 2 detector in 1.29, to ship in the next couple of days.
