### ISSUE TITLE
<3

### ISSUE THREAD

**Issue by ghuntley** [arkane-systems/genie#8]
We are looking at using this with https://github.com/NixOS/nixpkgs/issues/30391#issuecomment-505112269. Thanks for digging in and taking a stab at this problem space!

**Comment by cerebrate** [comment]
I hope it works for you!

I must confess to not having been previously familiar with NixOS, but it seems like a very interesting project which I'm now digging into. In the meantime, if there's anything I can do to assist with making genie work for you, please do drop me a line.
