### ISSUE TITLE
error executing command '/usr/libexec/genie/dumpwslenv.sh '

### ISSUE THREAD

**Issue by dark-swordsman** [arkane-systems/genie#80]
Hello,

I followed the instructions to build since I am using Ubuntu 20.04. I cloned the repo, got the dependencies I needed, and then ran `sudo make local` under `genie/genie`. 

However, I am running into the following error when I try to run `genie -i`:

```shell
genie: error executing command '/usr/libexec/genie/dumpwslenv.sh ':
No such file or directory
```

I found [this issue](https://github.com/arkane-systems/genie/issues/52) that has the same error, but it was fixed by some commits being re-introduced or something? Is this the same case here?

**Comment by pabo** [comment]
Same issue here. 

I'll also note that I'm only building from source due to the apparent rate limiting of the dist on packagecloud:

```
$ sudo apt-get update
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Err:3 https://packagecloud.io/arkane-systems/wsl-translinux/ubuntu focal InRelease
  429  Too Many Requests [IP: 54.215.161.51 443]
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
W: Failed to fetch https://packagecloud.io/arkane-systems/wsl-translinux/ubuntu/dists/focal/InRelease  429  Too Many Requests [IP: 54.215.161.51 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by cerebrate** [comment]
Oops. There was a bug in the makefile for the local build. Pull the latest changes and give it another try?

(Alternatively, you can download the package from the releases page and install it with `dpkg -i`.)

**Comment by pabo** [comment]
I chose the latter :) Thanks for your work!
