### ISSUE TITLE
Arch AUR links invalid

### ISSUE THREAD

**Issue by JonBoyleCoding** [arkane-systems/genie#82]
The links to the AUR packages point to invalid pages (404 page not found errors). Have they been taken down for good from the AUR?

**Comment by arlllk** [comment]
Yes, sorry but the folks of [Arch Linux decided to delete the package](https://lists.archlinux.org/pipermail/aur-requests/2020-September/044860.html). And now I don´t think how to maintain the package or anything. And currently I don't have the PKGBUILD, If anyone has it, contact me please.

**Comment by cerebrate** [comment]
...well, that's a kick in the head. And just when I was starting to make progress getting systemd-genie into Debian, too. 😢 Guess I'll need to take out the links.

I took a look around for the PKGBUILD, but I don't think I have it. If it turns up, I'll let you know.

**Comment by arlllk** [comment]
Maybe it could be included the PKGBUILD into the repo, maybe

**Comment by negezor** [comment]
I found a package in my cache
```sh
# Maintainer: Arley Henostroza <arllk10[at]gmail[dot]com>
# Contibutor: facekapow

pkgname=genie-systemd
_pkgname=genie
pkgver=1.23
pkgrel=3
pkgdesc="A quick way into a systemd \"bottle\" for WSL"
arch=('x86_64')
url="https://github.com/arkane-systems/genie"
license=('custom:The Unlicense')
depends=('daemonize' 'dotnet-runtime>=3.0' 'dotnet-host>=3.0' 'inetutils')
conflicts=('genie-systemd')
provides=('genie-systemd')
source=("${url}/releases/download/${pkgver}/${_pkgname}.tar.gz"
        'LICENSE')
sha256sums=('fbbd633b31cbc2cc8662ee47643e6b7c8ace8a1f296c0faab59bc10b6446de64'
            '88d9b4eb60579c191ec391ca04c16130572d7eedc4a86daa58bf28c6e14c9bcd')

prepare() {
  tar -xzf ${_pkgname}.tar.gz
}

package() {
  install -Dm 4755 -o root "systemd-genie/usr/bin/genie" -t "$pkgdir/usr/bin"
  install -Dm 644 -o root "systemd-genie/usr/bin/genie.dll" -t "$pkgdir/usr/bin"
  install -Dm 744 -o root "systemd-genie/usr/bin/Linux.ProcessManager.dll" -t "$pkgdir/usr/bin"
  install -Dm 744 -o root "systemd-genie/usr/bin/System.CommandLine.dll" -t "$pkgdir/usr/bin"
  install -Dm 744 -o root "systemd-genie/usr/bin/Tmds.LibC.dll" -t "$pkgdir/usr/bin"
  install -Dm 644 -o root "systemd-genie/usr/bin/genie.runtimeconfig.json" -t "$pkgdir/usr/bin"
  install -Dm 755 -o root "systemd-genie/lib/genie/dumpwslenv.sh" -t "$pkgdir/usr/lib/genie/"
  install -Dm 755 -o root "systemd-genie/lib/genie/readwslenv.sh" -t "$pkgdir/usr/lib/genie/"
  install -Dm 755 -o root "systemd-genie/lib/genie/runinwsl.sh" -t "$pkgdir/usr/lib/genie/"
  install -Dm 755 -o root "systemd-genie/lib/systemd/system-environment-generators/10-genie-envar.sh" -t "$pkgdir/usr/lib/systemd/system-environment-generators"
  install -Dm 644 "${srcdir}/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}

```

**Comment by negezor** [comment]
And the archive [genie.tar.gz](https://github.com/arkane-systems/genie/files/5251229/genie.tar.gz)

**Comment by JonBoyleCoding** [comment]
> Yes, sorry but the folks of [Arch Linux decided to delete the package](https://lists.archlinux.org/pipermail/aur-requests/2020-September/044860.html). And now I don´t think how to maintain the package or anything. And currently I don't have the PKGBUILD, If anyone has it, contact me please.
> 
> I had to write all of that without cursing, and it was very difficult

Don't worry about it, there are other means of getting this working :)

**Comment by ringosham** [comment]
Here's mine based on the latest version
```bash
# Maintainer: Arley Henostroza <arllk10[at]gmail[dot]com>
# Contibutor: facekapow

pkgname=genie-systemd
_pkgname=genie
pkgver=1.28
pkgrel=1
pkgdesc="A quick way into a systemd \"bottle\" for WSL"
arch=('x86_64')
url="https://github.com/arkane-systems/genie"
license=('custom:The Unlicense')
depends=('daemonize' 'dotnet-runtime>=3.1' 'dotnet-host>=3.1' 'inetutils')
makedepends=('dotnet-sdk>=3.1')
conflicts=('genie-systemd')
provides=('genie-systemd')
source=("${url}/archive/${pkgver}.tar.gz"
        'LICENSE')
sha256sums=('688253faad5e3c40c9277dac00a481f48bc5ed62cf2bc82c2c1234d92604ea96'
            '88d9b4eb60579c191ec391ca04c16130572d7eedc4a86daa58bf28c6e14c9bcd')

prepare() {
  tar -xzf ${pkgver}.tar.gz
}

package() {
  export DOTNET_CLI_TELEMETRY_OPTOUT=1
  export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  ls -alh
  cd genie-${pkgver}/genie
  export DESTDIR=$pkgdir
  make build
  make install
  install -Dm 644 "${srcdir}/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
  mkdir -p ${pkgdir}/usr/bin
  chmod +x ${pkgdir}/usr/libexec/genie
  ln -s /usr/libexec/genie/main/genie ${pkgdir}/usr/bin/genie
}
```

**Comment by cerebrate** [comment]
> Maybe it could be included the PKGBUILD into the repo, maybe

@arlllk I'm certainly not against the idea.

I've laid a little prep work for that by adding an arch build directory, with commands to run a makefile in that directory added to the top-level makefile, and a symlink in it such that `make -C genie` will work in there to build the executable. If the pkgbuild and a makefile can go in there and drop the package in the top-level folder, like the makefile for the debian build does, that'd be ideal.

**Comment by arlllk** [comment]
Sorry for the delay, I am very busy right now, and still quite hurt and discouraged by everything that has happened.

Thanks to @negezor, @ringosham for finding the PKGBUILDs, and to @JonBoyleCoding for the word (and reporting this), and of course @cerebrate to allow the integration of Arch directly in the repo.

I could find the PKGBUILD from the git version, but I don't really know how to integrate them in the makefile, when I find some time I will start to implement them, but for now I will upload both PKGBUILD if someone can help with the integration would be awesome.

[The link to the PKGBUILD](https://gist.github.com/arlllk/7001c521de601f01735af5ca440f03ae)

**Comment by cerebrate** [comment]
I've had a thought I'd like to play with. Does using this PKGBUILD require any dependencies over and above makepkg, on a fresh Arch install? I want to try doing a container-build so we don't need to do two builds independently.

**Comment by arlllk** [comment]
It only needs to install the group `base-devel` [[1]](https://wiki.archlinux.org/index.php/Creating_packages#Preparation), the file definition is on the [wiki of PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD).

The bigger part of my current job is been whit docker, CI, automation, and similar, I cloud help in some of that.

The PKGBUILD has two version one that is git version, that detects when a new commit is made, and recompiles the app, and can install it, the other, has to be manually updated every time there is an update (although it could be automatized if there have been no changes to the compiled files)

**Comment by cerebrate** [comment]
Still in progress.
