### ISSUE TITLE
Potential solution for #1

### ISSUE THREAD

**Issue by Mic92** [arkane-systems/genie#83]
I was reading over your bug list without having trying out genie, wsl2, etc, but you can potentially use `machinectl shell .host` to get a clean shell from systemd.

**Comment by Mic92** [comment]
Still valid.

**Comment by Mic92** [comment]
Consider switching to stale bot: https://github.com/probot/stale
This github does not really react to updates.

**Comment by cerebrate** [comment]
Sorry for the delay. My reaction usually isn't _quite_ so bad, but it's been a busy few months.

That's definitely an interesting idea, and it seems to work well. I'll need to check a few details (including the ubiquity of _systemd-machined_ as installed in common distros), but if that all works out, I'll look at switching to this for _genie -s_ in 1.29.

An option for _machinectl login_ might also be interesting...

**Comment by cerebrate** [comment]
Now included in 1.29 for all modes.
