### ISSUE TITLE
Unable to make genie

### ISSUE THREAD

**Issue by a3an-de** [arkane-systems/genie#84]
The first attempt sudo make local failed:
a3@LAPTOP-FFAQHMO7:~/genie/genie-master$ sudo make local
make: *** No rule to make target 'local'.  Stop.
The second attempt failed as well:
a3@LAPTOP-FFAQHMO7:~/genie/genie-master$ sudo make
make -C genie debian-pkg
make[1]: Entering directory '/home/a3/genie/genie-master/genie'
debuild
 dpkg-buildpackage -us -uc -ui
dpkg-buildpackage: info: source package systemd-genie
dpkg-buildpackage: info: source version 1.28
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Alistair Young <avatar@arkane-systems.net>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper-compat (= 13)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed
make[1]: *** [Makefile:48: debian-pkg] Error 29
make[1]: Leaving directory '/home/a3/genie/genie-master/genie'
make: *** [Makefile:9: package] Error 2

What can I do ?
Regards

**Comment by cerebrate** [comment]
You want to go down a level before running `make` - i.e., into the genie subfolder below the top-level folder. The top-level Makefile runs the packaging system; building (including local builds) is handled in the next level down.
