### ISSUE TITLE
apt: E: Unable to locate package systemd-genie

### ISSUE THREAD

**Issue by serle** [arkane-systems/genie#85]
Tried running: sudo apt install -y systemd-genie, returned, after entering sudo pwd:

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package systemd-genie

**Comment by elonderin** [comment]
same here ;(

**Comment by cerebrate** [comment]
Can you confirm whether the wsl-translinux repository is downloaded correctly when you run an _apt update_ ?

**Comment by cerebrate** [comment]
If you are using the repository hosted at Gemfly, this isn't working because the hosting company appears to have disappeared, taking our repo with it.

Please try again with the packagecloud.io repository now listed in the README.

**Comment by rabsym** [comment]
Trying packagecloud.io repository several days with no luck, any other way to get it? Thanks,

**Comment by cerebrate** [comment]
https://github.com/arkane-systems/genie/releases/tag/1.30

**Comment by rabsym** [comment]
> https://github.com/arkane-systems/genie/releases/tag/1.30

Thanks, just found, sorry for a newbie question.

**Comment by rabsym** [comment]
That version reports 1.29 (--version) thought should be and I think is 1.30, only to let you know.

**Comment by cerebrate** [comment]
Given the unfortunate tendency of packagecloud to run out of bandwidth, I have added a second repository here:

https://arkane-systems.github.io/wsl-transdebian/
