### ISSUE TITLE
Could we host a custom pacman repo for arch users?

### ISSUE THREAD

**Issue by rayfalling** [arkane-systems/genie#86]
Since AUR delete this package.
Maybe we can host a custom pacman repo for archlinux users?

**Comment by arlllk** [comment]
I think is possible, there is some open arch repositories, but it needs some server, and some security of using that server

**Comment by rayfalling** [comment]
I hava a vps， but I don't known how to server it(create an arch repo)

**Comment by cerebrate** [comment]
I'm not against such a thing existing and will happily list it in the install instructions, but none of my current package hosting services supports pacman repos, and I don't have time to take another one on.

**Comment by DuckSoft** [comment]
Not necessary now. I've put it into Arch Linux CN repository.
Just pick a mirror at https://github.com/archlinuxcn/mirrorlist-repo, sync, install `archlinuxcn-keyring` and `genie-systemd`, then you are ready to go. All dependencies are resolved and present.
