### ISSUE TITLE
Unable to use genie

### ISSUE THREAD

**Issue by GaussianWonder** [arkane-systems/genie#89]
# Nothing really happens

Even if I do `genie --version` i get back this:

```
Failure processing application bundle; possible file corruption.
Arithmetic overflow while reading bundle.
A fatal error occurred while processing application bundle
```

# Extra info
I use [Manjaro on WSL2](https://github.com/sileshn/ManjaroWSL)
The package was built by `makepkg -i` inside `./arch/`
Every dependency can be easily found on the AUR, the only one that looked weird is: [dotnet-sdk-preview](https://aur.archlinux.org/packages/dotnet-sdk-preview/)

```
> wsl --list --verbose
  NAME       STATE           VERSION
* Manjaro    Running         2
```

> I will also try building it again on a fresh installation

**Comment by cerebrate** [comment]
I'm no expert in Arch packaging (so, if @arlllk or @rayfalling would like to chime in at this point? 😃 It's certainly an extra thing to check in the Arch packaging process, #87), but I saw similar errors when I was working on the Debian package. 1.29 bundles additional .NET assemblies into the single genie executable, so when debhelper did its usual stripping of the executable as part of packaging, that broke it and caused it to give this error.

So, check that makepkg isn't doing anything to alter the compiled genie executable post-packaging?

Failing that, you can check if it's indeed a packaging problem by swapping out the packages' /usr/libexec/genie with a freshly compiled and published one (make in the lowest-level genie directory), or installing locally rather than as a package.

**Comment by rayfalling** [comment]
@GaussianWonder try this dotnet packeage [https://aur.archlinux.org/packages/dotnet-sdk-bin/](https://aur.archlinux.org/packages/dotnet-sdk-bin/), this is the release one.
I guess perview sdk may have some bugs unfixed?

**Comment by rayfalling** [comment]
@cerebrate I beg one of my friend add the package to archlinuxcn repo. so Archlinux users can add this repo and use package manager to install it.
Thanks to my friend @DuckSoft

**Comment by GaussianWonder** [comment]
I tried running `make` in the root dir, right after a `git clone` but it failed because it tried to run `make -C genie debian-pkg`.

So I tried this instead:

```
> make arch
make: 'arch' is up to date.
```

So I tried this instead:

```
> make -C arch arch-pkg
[. . .]
==> ERROR: /home/virghi/extras/genie/arch/genie is not a clone of https://github.com/arkane-systems/genie.git
    Aborting...
```

I see that the PKGBUILD gets copied to` /tmp/genie-makepkg/` but that folder is empty when it tries to `makepkg` it.

So I just copied the whole thing into `/tmp/genie-makepkg/` since it is only 4Mb even after building it.

```
==> ERROR: X is not a clone of https://github.com/arkane-systems/genie.git
    Aborting...
```

At this point I just jumped back `git-dir/genie` and ran
`sudo make install-local`
`sudo make install`

```
> genie --version
1.29
```

I think the problem could've been solved faster (using fewer commands) if I noticed that the `git-dir/arch/genie` folder is a symlink to `git-dir/genie/genie` beforehand.

The reason I posted this long ass comment is because:
1. Issue closed
2. I thought it might help you improve the installation scripts for arch. (even though it is not a necessity).

**Comment by DuckSoft** [comment]
FYI: `genie-systemd` is now available at [Arch Linux CN repository](https://github.com/archlinuxcn).
Mirrors: https://github.com/archlinuxcn/mirrorlist-repo
Quick Check: https://repo.archlinuxcn.org/x86_64/genie-systemd-1.29-2-x86_64.pkg.tar.zst

For maintainers: https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/genie-systemd/PKGBUILD

**Comment by rayfalling** [comment]
@cerebrate
> 1.29 bundles additional .NET assemblies into the single genie executable
this change makes it built success but excuted failed, we may consider revert the bundles build mode?

**Comment by cerebrate** [comment]
As suggested up above, this is likely a problem with the Arch packaging process, although I can't see anything in PKGBUILD that looks likely, inasmuch as the executable appears to work on other distros.

Can you check whether the executable coming out of the package is identical to the executable produced by the build?

**Comment by rayfalling** [comment]
I confirmed the option and fixed it, it will be released in next repo build
