### ISSUE TITLE
Waits forever for systemd

### ISSUE THREAD

**Issue by smitgd** [arkane-systems/genie#96]
v1.30 works OK for me with "wsl genie -i" 
Unable to update to v1.31 via apt due to server quota I assume.
Manually installed latest v.1.32 via dpkg as suggested.
Now "wsl genie -i" hangs forever printing waiting for systemd run state.
If I ctrl-c, it continues on and works.
Tried dpkg -i v1.31 with same results.
Reverted back to dpkg -i v1.30 and OK again. No wait for systemd prints.
Is this a feature or bug? Do I need to start systemd?
Minor side issue: v1.30 reports --version as v1.29.

**Comment by cerebrate** [comment]
It's a feature which makes sure that all your systemd services are running before you try to do anything that might require them.

You will probably find that if you wait the full 180 second timeout, 1.32 will error out telling you that one or more systemd units/services are not starting properly, i.e., not reaching the "running" state. You can confirm this with `systemctl status`; if I'm right, the state at the top should read "degraded", or something else other than running.

If you track down whichever units are not starting properly with `systemctl` and then either fix or disable them, it should work fine.

**Comment by smitgd** [comment]
Thanks for the quick response. Yes, I just now let it wait the full 180 seconds and it then continued on and worked as before. There were 5 failed services and state was degraded. With systemctl I was able to see the 5 failed services. Not sure what they all do but just setting the systemd timeout in /etc/genie.ini to 5 seconds pretty much returned it to the 1.30 startup behavior. Just for your info, I am running a full KDE desktop in wsl2.
Thanks again for the good info and s/w!

**Comment by cerebrate** [comment]
No problem!
